### ISSUE TITLE
Chroot some low level folder by default

### ISSUE THREAD

**Issue by fcpimenta** [Real-Gecko/Filemin#10]
Hi,

Firstly, congratulations for the good job and thanks for share it.

I'm intending to use filemin in FireServer project as the default file manager (www.fireserver.com.br).

I have an admin user with limited rights. Is there a way to limit and chroot the admin access to some folder by default? For example: for admin, the default chroot folder would be /app.

This will help me to protect top level directories like /etc and others. For Webmin's Java file manager, this is possible via module configuration.

Best regards,

Obs: Can I contact you via email?

Fernando Pimenta
pimenta@linux.com

**Comment by Real-Gecko** [comment]
I'm planning to implement moudle config and ACL soon. With ACL you'll have the ability to setup initial "chroot" folder.
Here is the list of things https://github.com/Real-Gecko/filemin/milestones I'm planning to do for 1.0 release.

**Comment by fcpimenta** [comment]
Thanks for the feedback.

I'll wait for the 1.0 version.

Fernando Pimenta

2015-06-03 1:30 GMT-03:00 Real-Gecko notifications@github.com:

**Comment by Real-Gecko** [comment]
ACL added in version 0.9.2.
Now you can setup allowed path on per user or per group basis.
