### ISSUE TITLE
Folder not download

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#101]
We are able to download the file but not able to download folder.

**Comment by Real-Gecko** [comment]
What version of Filemin do you use?

**Comment by vipin2079** [comment]
We are using webmin 1.791

**Comment by Real-Gecko** [comment]
I bet you're using Filemin bundled with Webmin, that's outdated.
[Here is the instruction](https://github.com/Real-Gecko/filemin/wiki) how to install latest version.
