### ISSUE TITLE
Updated Version ont installed on webmin.

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#102]
I am trying to updated latest version but found error after installing the filemin.

Can't locate version.pm in @INC (@INC contains: /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/filemin/index.cgi line 5. BEGIN failed--compilation aborted at /usr/libexec/webmin/filemin/index.cgi line 5.

**Comment by Real-Gecko** [comment]
Hmm, what distro do you use?

**Comment by vipin2079** [comment]
https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-1.1.1.linux.wbm.gz.

OS:Centos 7

**Comment by Real-Gecko** [comment]
What version of Perl is on your system?

**Comment by vipin2079** [comment]
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 29 registered patches, see perl -V for more detail)

**Comment by Real-Gecko** [comment]
That's strange, AFAIK version.pm is in da Perl core from version 5.9.0.
Try `yum install perl-version`

**Comment by iliaross** [comment]
You can find when a module was first included in the standard modules with this incantation: `perl -e 'use Module::CoreList; print Module::CoreList->first_release("version");'; echo`.

**Comment by vipin2079** [comment]
Please find log.Still I am fail to install latest filemin.

[root@IDCFM ~]# yum install perl-version
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
- base: mirror.nbrc.ac.in
- extras: mirror.nbrc.ac.in
- updates: mirror.nbrc.ac.in
  Resolving Dependencies
  --> Running transaction check
  ---> Package perl-version.x86_64 3:0.99.07-2.el7 will be installed
  --> Finished Dependency Resolution

Dependencies Resolved

# 

#  Package              Arch           Version                 Repository    Size

Installing:
 perl-version         x86_64         3:0.99.07-2.el7         base          84 k

# Transaction Summary

Install  1 Package

Total download size: 84 k
Installed size: 214 k
Is this ok [y/d/N]: y
Downloading packages:
perl-version-0.99.07-2.el7.x86_64.rpm                      |  84 kB   00:03
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 3:perl-version-0.99.07-2.el7.x86_64                          1/1
  Verifying  : 3:perl-version-0.99.07-2.el7.x86_64                          1/1

Installed:
  perl-version.x86_64 3:0.99.07-2.el7

Complete!
[root@IDCFM ~]# perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 29 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

[root@IDCFM ~]# perl -v

This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 29 registered patches, see perl -V for more detail)

Copyright 1987-2012, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

[root@IDCFM ~]# perl -e 'use Module::CoreList

> print Module::CoreList->first_release("version");'; echo
> Can't locate Module/CoreList.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at -e line 2.
> BEGIN failed--compilation aborted at -e line 2.

[root@IDCFM ~]#

**Comment by Real-Gecko** [comment]
`# corelist version`

**Comment by vipin2079** [comment]
Try but it's says not found

**Comment by Real-Gecko** [comment]
[There's an issue](https://bugs.centos.org/view.php?id=10352) in CentOS Bug Tracker, many people concern about Perl core in CentOS.
What's the output of `# corelist version` command?
If it does not work as intended I'll try to make a hotfix that will skip version checking

**Comment by vipin2079** [comment]
it's not working it's says output is:
login as: root
root@172.16.1.55's password:
Last failed login: Sat May 14 07:50:10 TLT 2016 from 183.3.202.102 on ssh:notty
There were 25426 failed login attempts since the last successful login.
Last login: Thu May 12 04:46:55 2016 from 172.16.2.112
-bash: corelist: command not found

**Comment by Real-Gecko** [comment]
Ok, I'll make version checking optional, so if there's no Version Perl module it won't fire.

**Comment by Real-Gecko** [comment]
I disabled version checking if Version module is unaccessible, grab the version 1.1.2.
