### ISSUE TITLE
Compress corrupted on zip mode

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#103]
I am trying to download the file in zip format & zip  file download on corrupted mode .

It's issue face only when i download file in zip file however not tar.gz file.tar.gz file successfully downloaded or extracted.

**Comment by iliaross** [comment]
Do you have fancy name for the `.zip` file? Like `lost+found hellow" there.zip`?

**Comment by vipin2079** [comment]
no simple it's a folder name which come automatically COFFEEV2 DATA TEMPLATE

**Comment by iliaross** [comment]
Hmm. Let's see what the dev says. I shouldn't be happening.

**Comment by iliaross** [comment]
You know, try renaming it to `COFFEEV2_DATA_TEMPLATE` if it works, then the issue is obvious.

**Comment by vipin2079** [comment]
Try that but issue still exist

**Comment by Real-Gecko** [comment]
What version of Filemin do you use?

**Comment by vipin2079** [comment]
Version 1.1.1

**Comment by Real-Gecko** [comment]
What if you download this file with FTP? Will it be corrupted too?

**Comment by vipin2079** [comment]
with FTP we can directly download the folder & it's successfully downloaded.
Even I download the zip file from FTP it's successfllut downloaded but with filemin it's not download on winzip format I assume it's convert the fail folder to zip file.

**Comment by Real-Gecko** [comment]
I do not actually understand what do you mean under corrupt zip file. How do you obtain it? Can you provide the file itself?

**Comment by vipin2079** [comment]
I am trying to dowload one folder.Two typer are appear zip or  tar.gz.When I select zip file then it's download  very soon but when trying to open the file it's says corrupt.

**Comment by Real-Gecko** [comment]
Show me this corrupt file.

**Comment by vipin2079** [comment]
I am not able to attach corrpted file even in mail also.Please find attach screen shot.
![capture_103](https://cloud.githubusercontent.com/assets/18715264/15300235/340a6174-1bc5-11e6-9c99-db10550a3426.JPG)

**Comment by Real-Gecko** [comment]
What's the size of the file? Can you view it's contents for example with Total Commander. I have no clue what's wrong with this file as I do not see it's contents.
