### ISSUE TITLE
File  Download Problem on click

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#104]
File is not able to download when we click on file however when we right  clink on file and download then file download but on left click file not download.

**Comment by Real-Gecko** [comment]
Version of Filemin?

**Comment by vipin2079** [comment]
Version 1.1.1

**Comment by Real-Gecko** [comment]
Can you provide reproduction scenario?

**Comment by vipin2079** [comment]
Please share your e-mail id so I wil provide you credential.

**Comment by Real-Gecko** [comment]
realgecko@realgecko.com

**Comment by Real-Gecko** [comment]
LOL, I've done those handy things like opening editor on clicking on text files, opening preview on images etc, and forgot to set default behavior to download for all others. Will fix that.

**Comment by Real-Gecko** [comment]
I've created the fix that will come to 1.1.3 release. For now you'll have to stick with right click. Or if you want so you can grab `unauthenticated` folder from this repo and place inside your Filemin installation, `/usr/share/webmin/filemin` usually.
