### ISSUE TITLE
Filemin not access after  install latest version

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#106]
I am trting to install latest version.It's says sucessfully installed but when i try to access it's says followng error:
Can't locate JSON/PP.pm in @INC (@INC contains: ./lib /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/ ..) at lib/Mojo/JSON.pm line 6.
BEGIN failed--compilation aborted at lib/Mojo/JSON.pm line 6.
Compilation failed in require at ./filemin-lib.pl line 12.
BEGIN failed--compilation aborted at ./filemin-lib.pl line 12.
Compilation failed in require at /usr/libexec/webmin/filemin/index.cgi line 4.

Operating System:Operating system CentOS Linux 7.2.1511 
Webmin version 1.801

**Comment by jcameron** [comment]
You should be able to fix this by running `yum install perl-JSON-PP`
