### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by MorningSleeper** [Real-Gecko/Filemin#108]
Link in following page to install filemin is broken.

https://github.com/Real-Gecko/filemin/wiki

**Comment by Real-Gecko** [comment]
Fixed

**Comment by MorningSleeper** [comment]
Thanks for fixing link, I get following when I try to install as per instructions

```
Downloading https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-2.0.0.linux.wbm.gz (160 bytes) ..
Downloading https://raw.githubusercontent.com/Real-Gecko/filemin/master/distrib/filemin-2.0.0.linux.wbm.gz ..
     Received 1 MB
.. download complete.
Failed to install module from https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-2.0.0.linux.wbm.gz : Not a valid module file : gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now 
```

**Comment by Real-Gecko** [comment]
Try opening link in your browser
https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-2.0.0.linux.wbm.gz
After download complete rename `filemin-2.0.0.linux.wbm.gz` to `filemin-2.0.0.linux.tar.gz`
And then try to open archive in archive manager.

**Comment by MorningSleeper** [comment]
Thanks, that worked.
