### ISSUE TITLE
get size of files under folder

### ISSUE THREAD

**Issue by engineer837** [Real-Gecko/Filemin#109]
Is there a way to get the total size of all the files under a folder, similar to the same feature in the Java based file manager? Thanks

**Comment by Real-Gecko** [comment]
Right click on da folder Tools -> Get Folder Sizes
![screenshot_20160707_183441](https://cloud.githubusercontent.com/assets/2231969/16653279/b4b4c7c2-4471-11e6-94bb-d16379de8d49.png)

**Comment by engineer837** [comment]
thanks but the theme I seem to have doesn't allow right clicking. Its integrated into webmin and looks different then the screenshot you posted.

**Comment by iliaross** [comment]
In case you mean Authentic Theme, make sure that you have latest version (18.03) and making right click, then going to the properties (at the bottom of the context menu) and clicking `Calculate Selected Size` will work for you.

**Comment by Real-Gecko** [comment]
https://github.com/Real-Gecko/filemin/wiki
Here is da instruction of how to install latest version of Filemin.

**Comment by engineer837** [comment]
got this response when I did the above: Failed to install module from https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-2.0.0.linux.wbm.gz : Not a valid module file : gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now

**Comment by iliaross** [comment]
There is a Webmin [fix](https://github.com/webmin/webmin/commit/941f110edaa1d2f2917184a216a428e904dec139) for it. Other way to install it is using upload (first donwload it to your local PC)

**Comment by Real-Gecko** [comment]
OK, it is Webmin's problem then. Download the file manually, navigate to "Webmin - Webmin Configuration - Webmin Modules", check "From uploaded file" radio button and select downloaded file.

**Comment by iliaross** [comment]
It's actually GitHub voluntarily doing things.

**Comment by engineer837** [comment]
direct upload did it- many thanks to both of you- big improvement. It opens to an intermediate page, then "filemin will open in new tab" but I have to open it. Not a big deal at all- can live with that. Thanks again

**Comment by Real-Gecko** [comment]
Your browser must be blocking popup windows, add your server to exception list and you'll be fine.

**Comment by engineer837** [comment]
I unblocked the pop-up window and it comes right up- perfect

**Comment by engineer837** [comment]
Can I install filemin in earlier versions of webmin without a problem? Does it need a minimum version?

**Comment by Real-Gecko** [comment]
When Filemin was initially developed Webmin was somwhere in 1.6\* as far as I can remember, first public release was tested with Webmin 1.710. So I bet you won't encounter any problems with earlier versions of Webmin. Especially now when Filemin does not rely on Webmin's ui-lib.pl.

**Comment by engineer837** [comment]
works perfectly in my other 2 webmin installations- thanks

**Comment by Real-Gecko** [comment]
You're welcome!
