### ISSUE TITLE
End of line character '\r'

### ISSUE THREAD

**Issue by PurpleEdge2214** [Real-Gecko/Filemin#11]
I received an error that an invalid character was found in a file after editing .bash_profile - the character was '\r' - dos end of line marker.

I don't know if it came from a cut and paste, or from filemin.

Would be nice if filemin stripped these characters when saving the file.

I was only able to remove it by using dos2unix.

**Comment by Real-Gecko** [comment]
I think it came from edit form in edit.cgi, did you work under winduz when edited the file?

**Comment by PurpleEdge2214** [comment]
I was running firefox, on a WIndows PC.

**Comment by Real-Gecko** [comment]
I will deal with it in next minor release.

**Comment by Real-Gecko** [comment]
Fixed in 0.9.2
