### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#110]
Earlier Java File Manager, we are adble to rediect to user on particular folder but in filemin we are not able to redirect to user on particular even  file setting is present.

**Comment by Real-Gecko** [comment]
I'm not sure I understand what you mean

**Comment by vipin2079** [comment]
Example 
 A user can access the folder VIPIN then it's automatically redirect to VIPIN Folder  when he will login in filemanager with A User which present in system.

B User can access the folder Real-Gecko Directory when user login throgh file min it's automatically redirect to Real-Gecko.

Here all user  redirect only one folder.

**Comment by Real-Gecko** [comment]
In earlier verions of Filemin user was redirected to the folder he was locked in - usually user's home dir. In latest version Filemin remembers each users's opened tabs and restores them on restart. So if you were working in `/home/realgecko/public_html` in one tab and `/usr/share/webmin` in second one, then as soon as you restart Filemin both tabs will be restored, so you can continue working with'em.

**Comment by vipin2079** [comment]
Sorry for confustion:
Please do following  scenario:
I created one user in webmin with Vipin Name and  One Folder is Business so i want when user  logged in webmin  & click on filemin it's need to goes Business  Folder.
One other folder user in webmin with real name and one folder is Orange so if user logged in webmin & click on filemin it's need to goes Orange Folder.

**Comment by vipin2079** [comment]
This  otion available in JAVA FILE MANAGER.

**Comment by Real-Gecko** [comment]
If you go to `Webmin->Webmin Users->{user_name}->Available Webmin Modules->Filemin` you can set the user's "chroot" directory. It's the directory he will be locked in. Where he will be redirected later is his own business, as each user has his own persistence of places he gone before
![screenshot_20160716_042711](https://cloud.githubusercontent.com/assets/2231969/16890150/d43e5610-4b0d-11e6-8513-140d24e90505.png)
