### ISSUE TITLE
Error:Permisstion Module

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#111]
Try to work on issue number110
Require filemin/acl_security.pl failed :
Can't locate File/MimeInfo.pm in @INC (@INC contains: ./lib /usr/libexec/webmin/filemin /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/ ..) at /usr/libexec/webmin/filemin/filemin-lib.pl line 11.
BEGIN failed--compilation aborted at /usr/libexec/webmin/filemin/filemin-lib.pl line 11.
Compilation failed in require at /usr/libexec/webmin/filemin/acl_security.pl line 1.

**Comment by Real-Gecko** [comment]
Until this [fix](https://github.com/webmin/webmin/commit/941f110edaa1d2f2917184a216a428e904dec139) is released you'll have to update Filemin manually.

**Comment by ovizii** [comment]
Seems to be a problem and unsolved. I am running Webmin 	1.840 and all modules are up to date. I created a webmin groupthen went to edit it: webmin => webmin users => click on group name => available webmin modules => file manager is selected

a click on "File manager" brings up this error:

Require filemin/acl_security.pl failed :
```
syntax error at /usr/libexec/webmin/filemin/acl_security.pl line 9, near "ui_textarea"
syntax error at /usr/libexec/webmin/filemin/acl_security.pl line 33, near "}"
Can't use global @_ in "my" at /usr/libexec/webmin/filemin/acl_security.pl line 36, near "= @_"
syntax error at /usr/libexec/webmin/filemin/acl_security.pl line 62, near "}"
```

**Comment by Real-Gecko** [comment]
What version of Filemin?

**Comment by ovizii** [comment]
OK, might be my mistake. I had not specifically installed FileMin. I was referring to webmin dashboard => Others => File manager (not sure how to find out its version. 

I now downloaded: https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-2.1.0.linux.builtin.wbm.gz and isntalled it. 

If I now go to webmind dashboard => others => Filemin File Manager I get:

Error - Perl execution failed

`Can't locate Digest/SHA.pm in @INC (@INC contains: ./lib /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/ .. .//lib) at lib/Mojo/Util.pm line 7. BEGIN failed--compilation aborted at lib/Mojo/Util.pm line 7. Compilation failed in require at lib/Mojo/JSON.pm line 7. BEGIN failed--compilation aborted at lib/Mojo/JSON.pm line 7. Compilation failed in require at ./filemin-lib.pl line 18. BEGIN failed--compilation aborted at ./filemin-lib.pl line 18. Compilation failed in require at /usr/libexec/webmin/filemin/index.cgi line 4.`

Then I found this info:

> To avoid the issue since version 2.0.0 Filemin installs additional Filemin Updater module. Just click "Filemin Updater" option in "Others" menu of Webmin to reinstall Filemin.

but I do not have the "Filemin Updater" menu.

Any ideas?

**Comment by Real-Gecko** [comment]
Navigate to `Webmin - Webmin Configuration - Webmin Modules` and hit `Export` tab, find `Filemin` in dropdown, you'll be able to see installed version.
![screenshot_20170516_183930](https://cloud.githubusercontent.com/assets/2231969/26106372/8dcdd09e-3a67-11e7-9cee-0dc9aefc9cc7.png)

**Comment by ovizii** [comment]
weird I do not have a dropdown: 
![filemin](https://cloud.githubusercontent.com/assets/837902/26106624/bc9a7f7e-3a46-11e7-9942-54a45088337c.png)

**Comment by Real-Gecko** [comment]
Ah yes, you use Authentic Theme, that's why you don't have dropdown :D
What OS do you use?

**Comment by ovizii** [comment]
CentOS Linux 6.9

**Comment by Real-Gecko** [comment]
Crap, CentOS 7 had some problems I had to fix and I'm 100% sure 6.9 has even more :D
Anyways, let's try to beat your problem: try installing perl module Digest::SHA, I think `yum install perl-Digest-SHA` will work.

**Comment by ovizii** [comment]
I just did that and even restarted Webmin. Getting this now: 
![filemin2](https://cloud.githubusercontent.com/assets/837902/26110474/c2d74a96-3a52-11e7-91b3-ce8e8f74e66f.png)

fixed with: yum install perl-Time-HiRes finally it loads :-)

**Comment by Real-Gecko** [comment]
Nice :)
