### ISSUE TITLE
New Session not created

### ISSUE THREAD

**Issue by vipin2079** [Real-Gecko/Filemin#113]
When I login again i found bank data screen and giving message create new session but new session is not coming.When click on + icon then it's shows new session.
![capture_filemin_v1](https://cloud.githubusercontent.com/assets/18715264/16902322/ef95fc2a-4c29-11e6-9d74-0ea04eea166e.PNG)
![capture_filemin](https://cloud.githubusercontent.com/assets/18715264/16902323/ef96510c-4c29-11e6-8e85-c0d5fc6cd8cf.PNG)

**Comment by Real-Gecko** [comment]
That's because you switched from old Filemin to new one. If you restart Filemin your session will be restored.
