### ISSUE TITLE
[Feature Request] Add option to clone git repo to current folder

### ISSUE THREAD

**Issue by singhdd93** [Real-Gecko/Filemin#116]
Thanks a lot for a great module.
I have a feature request. Can we have a option to clone public repos to current folder just like we have option to download file from URL.

Thanks a lot in advance

**Comment by jcameron** [comment]
Do you mean clone a repo to a file on the server?

**Comment by Real-Gecko** [comment]
I do not think that adding such functionality is required, as each CVS is complex by itself and trying to create interface that includes all options worth separate project.
Webmin itself contains `Custom Commands` module  (Webmin - Others - Custom Commands), that may be used to provide shell like interface to execute things such as `git clone`.
If you're looking for WebIDE you may find [Codiad](https://github.com/Codiad/Codiad) usefull.
It has various plugins for control version systems interaction and much more.
I use it right now for Filemin development.

**Comment by Real-Gecko** [comment]
Oops.
Not `Custom Commands`, but `Command Shell` - Webmin -> Others -> Command Shell.

**Comment by singhdd93** [comment]
@jcameron Yes, Exactly.

The thing is I have most of the wordpress users and some plugins are to be cloned from git. These guys are not comfortable with command line.
I had already expected the similar response as I know that this would be quite complex. 

Thanks a lot

**Comment by Real-Gecko** [comment]
Oh man, use [Drupal](https://www.drupal.org/). It's learning curve is quite steep, but it worth it :D
You can even install any module from admin interface
![screenshot_20160901_162828](https://cloud.githubusercontent.com/assets/2231969/18164390/6436d56c-7061-11e6-8055-bd1622aa22de.png)
;)

**Comment by Real-Gecko** [comment]
Maybe you can organize something like your own plugin's repo?
Nice addition to your hosting service ;)
