### ISSUE TITLE
Filemin Updater

### ISSUE THREAD

**Issue by singhdd93** [Real-Gecko/Filemin#117]
I have installed Filemin File Manager using wbm.gz file for Linux on CentOS 7. But I dont see any module "Filemin Updater"

**Comment by Real-Gecko** [comment]
You have to start Filemin once as root, after that Filemin Updater will be installed.
Considering overall Webmin working concept update is available for root only too.

**Comment by singhdd93** [comment]
Oh thats the reason. I basically use Virtualmin/Webmin with sudo user rather than root. 
Thanks for the info. Gonna try it

**Comment by Real-Gecko** [comment]
You're welcome :)
