### ISSUE TITLE
Support SELinux chcon and 'ls -Z' in main/context menu

### ISSUE THREAD

**Issue by clawrie** [Real-Gecko/Filemin#120]
With more servers moving to Centos 7 and other flavours that implement SELInux, it would be great if we were able to display and control labelling/contexts from within Filemin.
I've moved the home folder and database folders to a separate volume in my system and having SELinux management within Filemin would have made it easier to resolve  my issues.

**Comment by iliaross** [comment]
I will try adding it to bundled Filemin version as I also prefer having it displayed.

**Comment by Real-Gecko** [comment]
It is here!
https://github.com/Real-Gecko/Filemin/releases/tag/v2.1.0
Have fun :D
