### ISSUE TITLE
Bookmarks are offscreen

### ISSUE THREAD

**Issue by cmroanirgo** [Real-Gecko/Filemin#125]
Hopefully, the title say it all.

If you have a bookmark for a very deep folder, you cannot see any of them:
![offscreen](https://cloud.githubusercontent.com/assets/15967/21486312/9442e63c-cc06-11e6-9892-ddf58ec17d6d.png)

**Comment by Real-Gecko** [comment]
Browser?

**Comment by cmroanirgo** [comment]
My bad. 
Happens on OSX, in Chrome 55 and FFox 50.1 and Safari 8.
All look exactly the same.

This is with Filemin v2.1.0

**Comment by Real-Gecko** [comment]
OK, got it.
Can you provide path example?
You can find all your bookmarks in `~/.filemin/.bookmarks`, how many symbols is the longest one?
Can you reach edit bookmarks button?

**Comment by cmroanirgo** [comment]
(I figured out that the 2nd one down was manage bookmarks. It works normally.)

This is my longest string (all the others are rather modest: `/var/log` kind of stuff):

`/home/xxxxx_xxxxxxx/private/next_data/rainloop-storage/_data_/_default_/plugins`

By my count that's **80** chars.

**Comment by Real-Gecko** [comment]
OK.

**Comment by Real-Gecko** [comment]
Fixed in 2.2.0.
