### ISSUE TITLE
Doesn't work in usermin?

### ISSUE THREAD

**Issue by cmroanirgo** [Real-Gecko/Filemin#126]
When installed into usermin, the original file manager is overwritten (as expected), but the user sees the error: 'Module webmin does not exist' when selecting it from the side menu.

![filemin](https://cloud.githubusercontent.com/assets/15967/21486509/f0d2bed8-cc09-11e6-9c29-a3245027393d.png)

By forcing a visit to the (new) filemin url:
https://example.com:20000/filemin/filemin.cgi
No files nor folders are shown:

![filemin2](https://cloud.githubusercontent.com/assets/15967/21486658/6f8d4da4-cc0c-11e6-9aa3-ab02907f7790.png)

When I revert back to the old v0.9.6, it all works as expected.

EDIT: If install v1.1.2, and then v.2.10 *without deleting the previous v1.1.2*, I can get it to work. Of course, I have duplicate 'Filemin File Manager' entries in my usermin menu when I do this.

**Comment by Real-Gecko** [comment]
I'll check that.

**Comment by brianforan** [comment]
@Real-Gecko any update on this? Ran into this problem today and figured we'd just have to use filemin with Webmin users restricted, but having some issues there as well.

**Comment by snickers2k** [comment]
same here. but not using usermin. i have an empty filemin with webmin :/ says sucessful loaded, but still empty.
where to find logs that could help?
thanks

**Comment by Real-Gecko** [comment]
Fixed in 2.2.0.

**Comment by Real-Gecko** [comment]
Alright! Something went wrong and version 2.2.0 did not work in Usermin, however a little change for 2.2.1 made it work. Have fun!
