### ISSUE TITLE
Replace files and folder instead of creatng _copy

### ISSUE THREAD

**Issue by kamilmedia** [Real-Gecko/Filemin#127]
Hi
I use the lastet Filemin 2.1 and I want to replace folders and files by others, not creatng a _copy files and folders? there is somethng to do in configuration to achieve that?

kind regards Zak

**Comment by Real-Gecko** [comment]
I'll see what I can do.

**Comment by Real-Gecko** [comment]
New option in `Buffer` submenu called `Paste overwriting` is now available.
Grab versio 2.2.0.
