### ISSUE TITLE
Error 200

### ISSUE THREAD

**Issue by engineer837** [Real-Gecko/Filemin#128]
Hello- I see Error!!! 200 [object Object] whenever I try to browse one particular folder (/etc/ssl/certs), and that folder won't open. Other servers work fine on that same folder, with the same O/S and version of Filemin (2.1.0). Thanks

**Comment by Real-Gecko** [comment]
Do you have permission to access that particular folder?

**Comment by engineer837** [comment]
Yes, I am logged in as root. The owner of the folder is root, group is root and permission are 0755, same as my other servers that do work.

**Comment by Real-Gecko** [comment]
What about accessing the folder while connected through SSH?

**Comment by engineer837** [comment]
No problem

**Comment by Real-Gecko** [comment]
Try to grab the response with Firebug.

**Comment by engineer837** [comment]
I don’t know how to use Firebug, and they don’t support the extension in my version of Firefox anymore, but I did turn on the Console in Safari and got the attached errors when opening Filemin, without even going to the problem folder. These Filemin errors do not show up on my other servers.

**Comment by Real-Gecko** [comment]
What's the exact server response?

**Comment by engineer837** [comment]
When I open Filemin, it opens normally with no errors. I can browse to all the folders I have tried, and use all the Filemin functions. But when I try to go to etc/ssl/certs, Filemin gives the response: Error!!! [200 Object object] in a small window, lower right and the folder does not open- the window stays on the parent folder.

**Comment by engineer837** [comment]
The problem was caused by a corrupt file in the /etc/ssl/certs folder. I only know it is a .pem file, but finding the exact file has been a challenge. Meanwhile I have only populated the certs folder with the .pem files I think are essential. Filemin is not directly implicated in this problem. Thanks for your help.
