### ISSUE TITLE
Can not see extract option

### ISSUE THREAD

**Issue by xtensions** [Real-Gecko/Filemin#132]
Just installed filemin on webmin on debian 8. I can see all other options except extract/unzip. Am I missing something.

**Comment by Real-Gecko** [comment]
Any screenshots?

**Comment by xtensions** [comment]
<img width="883" alt="screen shot 2017-06-14 at 6 45 27 pm" src="https://user-images.githubusercontent.com/14876525/27133987-ba35ef46-5131-11e7-9c6d-8824149fcf5b.png">
<img width="648" alt="screen shot 2017-06-14 at 6 45 20 pm" src="https://user-images.githubusercontent.com/14876525/27133988-ba3b1e80-5131-11e7-9361-76d0fffbcd49.png">

**Comment by Real-Gecko** [comment]
apt-get install shared-mime-info

**Comment by xtensions** [comment]
Thanks works like charm, sorry to miss that.

**Comment by Real-Gecko** [comment]
You're welcome :)
