### ISSUE TITLE
Large file delete issue

### ISSUE THREAD

**Issue by Lolcsi** [Real-Gecko/Filemin#133]
I found a bug large file 5GB+ deleting it does not happen. File Manager not responding or freeze.

**Comment by iliaross** [comment]
Hi,

What system are you running and what architecture is that? What is the filesystem?


---


I just made a test and deleted **~78Gb file**, and all worked as expected - the file was deleted.

**Comment by Lolcsi** [comment]
Hi qooob!

Ubuntu Linux 14.04.3
Webmin version | 1.851
Usermin version | 1.720
Virtualmin version | 5.99
Theme version | Authentic Theme 18.49-8
Kernel and CPU | Linux 3.13.0-24-generic on x86_64
Processor information | Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz, 4 cores
Filesystem | ext4

I tested on virtualmin backup file!

**Comment by iliaross** [comment]
I also tested it with `ext4` but on RHEL. Are you sure the file size is the issue? If you try to change directory does it work correctly? 

Do you maybe get errors in the console? If so, could you share the screenshot?

**Comment by Lolcsi** [comment]
Yes I deleted many smaller file

**Comment by iliaross** [comment]
Still, do you have errors in console? Can you try again?

**Comment by Lolcsi** [comment]
![stuck deleting](https://user-images.githubusercontent.com/23224558/28678030-9252e314-72ef-11e7-991d-03f289562f7f.jpg)

**Comment by Lolcsi** [comment]
stuck in this screen and I waiting 10 min but nothing happened. I try deleting smaller file this folder its working.

**Comment by iliaross** [comment]
Moved: https://github.com/qooob/authentic-theme/issues/827

**Comment by Real-Gecko** [comment]
Grab Filemin 2 it has no such issues.
