### ISSUE TITLE
Treeview

### ISSUE THREAD

**Issue by LWSRep** [Real-Gecko/Filemin#134]
Probably not the right section but couldnt find anywhere else to post this
i would really like a tree view structure like in windows explorer or total commander.
i use filemin every day moving and editing files and treeview would speed up my work a lot

**Comment by iliaross** [comment]
Hi,

The tree view in File Manager (that is shipped with Webmin) will be added after Authentic Theme 19.00 final release. 

Non-forked version of Filemin 2+ has it already, so you could try installing it from this repo.

**Comment by Real-Gecko** [comment]
Treeview 've been around since [version 1.1.0](https://github.com/Real-Gecko/Filemin/blob/master/CHANGELOG.md#added-3), just grab the latest release and don't forget about [update instructions](https://github.com/Real-Gecko/Filemin#update).
