### ISSUE TITLE
Perl execution failed : Experimental pop on scalar is now forbidden at /usr/share/webmin/filemin/paste.cgi line 29, near "@p)"

### ISSUE THREAD

**Issue by xtensions** [Real-Gecko/Filemin#135]
I am not able to paste any file at any path, despite having correct owner and permissions at the folder. The miniserv.error displays this message. 
`miniserv.error 
/filemin/paste.cgi : Perl execution failed : Experimental pop on scalar is now forbidden at /usr/share/webmin/filemin/paste.cgi line 29, near "@p)"`

I am using webmin on Debian 9 fresh install. When I paste using filemin I get the paste error. 

please note this also happens with when i use copy paste on cyberduck using sftp connection so maybe a server config on debian 9, but any help is appreciated. I have installed filemin and webmin on many debian 8 machines, but never had this issue. Its just coming on fresh debian 9 installation.

![filemin_paste](https://user-images.githubusercontent.com/14876525/29072621-0bd993b6-7c66-11e7-8e71-e882c47e53be.png)

**Comment by xtensions** [comment]
An update with regards to cyberduck, I updated the application and it has fixed the issue of paste for that application but filemin still has the issue. 

`/filemin/paste.cgi : Perl execution failed : Experimental pop on scalar is now forbidden at /usr/share/webmin/filemin/paste.cgi line 29, near "@p)"`

Line 29 is:
`my $name = pop(\@p);`

Also if I use default file manager in usermin module of webmin, than paste works fine. Debian 9 comes with perl 5.24. So this has to be corrected in filemin for perl 5.24

I dont have any idea how perl works, but may be worth looking into : 
1) https://github.com/XavierBerger/RPi-Monitor/issues/157
2) https://www.google.co.in/search?client=safari&rls=en&q=Experimental+pop+on+scalar+is+now+forbidden+at&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=bCiKWd7aMvDI8AfZrK6QAQ

**Comment by swelljoe** [comment]
I don't have familiarity with this code, but...

Passing a reference to an array to pop doesn't make sense. It would either need to be:

    pop(@p)

Or:

    pop(@{$p})

The latter would be if there is a reference to the array in $p, the former if @p is an array.

The \ syntax creates a reference, which is a scalar (and can't sensibly be popped).

**Comment by Real-Gecko** [comment]
Fixed in 2.1.1
