### ISSUE TITLE
chroot/restrict file manager to a spesific folder

### ISSUE THREAD

**Issue by drphlux** [Real-Gecko/Filemin#139]
Hello Alexandr.
I'm looking for a way to "lock" the File Manager to a specific folder,
so that even users working as root only sees /ftpdata or something similar. 
I would like those users NOT to be able to browse files in any other 
place but /ftpdata 

I believe the old java file manager had this option? ( root=/folder )

**Comment by Real-Gecko** [comment]
Navigate to Filemin module page and click `Module Config` link, you'll see list of directories accessible to users. $HOME counts as user home directory, any other paths are just usual paths.
If you want to configure access on per user basis, navigate to `Webmin Users` -> `<username>` -> `Available Webmin modules`->`Others` and click `Filemin File Manager`, you'll see the same list of directories user can access.
However `root` bypasses all restrictions of ACL. Be carefull.
