### ISSUE TITLE
How to clear session data 

### ISSUE THREAD

**Issue by hinhthoi** [Real-Gecko/Filemin#140]
Sorry, maybe it is not a good idea to ask for this feature. Please help delete this post.

**Comment by hinhthoi** [comment]
I guess I need to edit the file filemin.js or filemin.min.js, but I'm a noob in javascript. Hope somebody can help me out.

**Comment by Real-Gecko** [comment]
The only way to clear session data is to use another file manager on your server, like Midnight Commander(CLI) or Krusader(DE), or to use `root` account. It is stored in `~/.filemin` directory.

**Comment by Real-Gecko** [comment]
If you want to navigate to your $HOME everytime Filemin starts, then just leave appropriate tab open before closing Filemin, or use bookmarks for fast navigation.
