### ISSUE TITLE
"Show # Entries" File Manager default

### ISSUE THREAD

**Issue by FBachofner** [Real-Gecko/Filemin#142]
In "Configuration For module File Manager" there does not seem to be a way to change the default "Show # Entries" in Webmin's File Manager.

There is also apparently no way to do this for AuthenticTheme (assuming the theme could manipulate the dropdown).

Is there a text file somewhere which controls this #? [25, the default, is frustratingly low for me].

Also, would you consider this as an enhancement request (even if there is a text file which can be edited to set a different default)?

Thanks in advance and continued thanks for this superb project!

**Comment by Real-Gecko** [comment]
Which version do you use?

**Comment by FBachofner** [comment]
@Rael-Gecko:

I am on Webmin 1.880 and using whatever version of the built-in file manager it comes with.  How can I identify the file manager version # further?

Also, an interesting tidbit: when I click on the gear button to configure the file manager module, sometimes I see a flash of a screen which indicates (I think . . . it disappears _very_ fast) the default # of files can be changed but "in old themes only" [ I have been using Authentic Theme since early betas ]

**Comment by iliaross** [comment]
@FBachofner You're using default/official version of File Manager (filemin 0.96+), as with Webmin we use/ship forked version.

You can install version 2+ from this repo, but it's not supported by Webmin's default theme and will have to work on the new/separate tab, with different look and functionality. For bundled File Manager, you could report a bug or create feature request to [Authentic Theme](https://github.com/qooob/authentic-theme) or to [Webmin](https://github.com/webmin/webmin/) repo.

**Comment by FBachofner** [comment]
@qooob  Thank you.  I thought this repo _was_ for the official version of File Manager.

As you suggest, I'll post an enhancement request to the Webmin page and consider trying your project when I find some time over the next few weekends.

**Comment by iliaross** [comment]
@FBachofner Please be kind providing screenshots, as it would speed up things up.

**Comment by FBachofner** [comment]
@qooob:  Hi Ilia

Could you confirm what you need screenshots of / for ?  [ Are you asking for a mock-up ? ]

I have just put through enhancement requests to
Webmin: https://github.com/webmin/webmin/issues/857
and
Authentic Theme: https://github.com/qooob/authentic-theme/issues/1048

I just envision being able to set a # default in (preferably) "Configuration For module File Manager" **_or_** (if it "has" to be done in Authentic Theme for some reason) perhaps add a configuration section at "/webmin/edit_themes.cgi" -- the section could be descriptively named "File Manager" and other default configuration options could be added there.

Thanks!

**Comment by iliaross** [comment]
I could add options directly to File Manager's configuration.

Is this okay if we just make it remember position/sorting, without any extra options?

**Comment by FBachofner** [comment]
@qooob:
I think that's great!

This would be the logical place to find the configuration option.

**Comment by Real-Gecko** [comment]
Update to the latest version it shows all entries by default.

**Comment by FBachofner** [comment]
@qooob  @Real-Gecko 

> shows all entries by default

That's an interesting approach.  It works for me :-) as my connections are either local or relatively fast.

Some people may not like it, however.  It will be interesting to hear the feedback.

**Comment by iliaross** [comment]
@FBachofner Me and Real-Gecko are talking about two different branches of File Manager.

What did you mean in your last comment? It's not clear.

**Comment by FBachofner** [comment]
@qooob Sorry, I thought you were assisting @Real-Gecko with his version since you were also posting to this thread:
https://github.com/Real-Gecko/Filemin/issues/142

it was only @Real-Gecko mentioned
> shows all entries by default.

As you know, _your_ branch now allows users to set a default # of entries to be displayed, which I have really been enjoying!
