### ISSUE TITLE
Request: Symlinks

### ISSUE THREAD

**Issue by snickers2k** [Real-Gecko/Filemin#146]
Would be great to have the ability to symlink inside Filemin. Thanks

**Comment by Real-Gecko** [comment]
There's already one:
1. select file/folder you want to symlink
2. right click it and select _**copy**_
3. navigate to destination
4. right click and select _**paste symlink**_
5. ????
6. PROFIT!!!111oneoneone

**Comment by iliaross** [comment]
@snickers2k You probably talking about shipped version of File Manager (Filemin 1x) - it's on [my todo](https://github.com/authentic-theme/authentic-theme/issues/629#issue-198498774).

**Comment by iliaross** [comment]
@snickers2k The support for creating symlinks was added - https://github.com/authentic-theme/authentic-theme/issues/629#issuecomment-426615864

**Comment by snickers2k** [comment]
thank you!

**Comment by Real-Gecko** [comment]
Reinventing the wheel :D
