### ISSUE TITLE
Error 500 Perl execution failed

### ISSUE THREAD

**Issue by SylvainLegrand** [Real-Gecko/Filemin#148]
Hi,

Both Ubuntu 18.04 and 16.04
Webmin 19.34
filemin 2.2.3 linux full

When I click on the link to open and use the module is loaded in a new tab (OK) but in te main webmin tab  I find this error message : "**Error 500 Perl execution failed - undefined subroutine &extensions::get_selinux_command_type called**"

Greetings,
Sylvain Legrand.

**Comment by rtahina** [comment]
Hi,

I'm running into the same problem. Has anyone found a fix or a work-around?

Regards,

Lita

**Comment by Real-Gecko** [comment]
This happens only with Authentic Theme.

**Comment by SylvainLegrand** [comment]
Hello,

Which theme should we used ?

**Comment by Real-Gecko** [comment]
Any other bundled with Webmin. Or you may try great [BWTheme](http://theme.winfuture.it/)
