### ISSUE TITLE
Files Create, move, rename, ect. 

### ISSUE THREAD

**Issue by JoergXX** [Real-Gecko/Filemin#150]
Hello,
since the last Webmin update i can not create, move or rename Files. 
When i create a file "Test.pm", I get an error message : No such file or directory. The directory exists

Regards Jörg

**Comment by Real-Gecko** [comment]
Install latest version from [here](https://github.com/Real-Gecko/Filemin/releases).
This will also coinstall Filemin Updater module, use it to install latest version every time Webmin updates.
