### ISSUE TITLE
Would like to edit .sk file with webmin.

### ISSUE THREAD

**Issue by loprima-l** [Real-Gecko/Filemin#151]
for the moment we can only see the .sk files, and that is sad.
(.sk files = skript mc files) and i will be very happy if we can edit this thanks, Loprima

**Comment by Real-Gecko** [comment]
What is the mime type of this file returned by Filemin?

**Comment by Real-Gecko** [comment]
Which files can be edited is decided on client side by Code Mirror, one temporary workaround the problem would be to rename file from `myscirpt.sk` to `myscript.txt`, this way file will be marked as editable, and you can then edit it. However Code Mirror might be not able to highlight syntax and do other fancy staff. Play with code mirror file types to find maybe acceptable language mode for .sk files. After editing simply rename file back to `myscript.sk`.
