### ISSUE TITLE
Access root folder / Get out of home-directory

### ISSUE THREAD

**Issue by Braintelligence** [Real-Gecko/Filemin#16]
Hey there :)
I'm using webmin for the first time and trying to figure out everything. Since NPAPI plugins won't be supported by Chrome pretty soon I was very glad to find your filemin, so I can use a file manager that still works.

One thing I'm wondering is how I can get out of the home directory when using filemin. There is no ".." or anything that is obviously navigating me out of there...

**Comment by Real-Gecko** [comment]
In version 0.9.2 ACL was added, you have to navigate to `Webmin->Webmin Users->$YOUR_USERN_NAME->Available Webmin modules (in addition to those from group)` and click Filemin. You will see "Filemin access control options", input desired paths here, like /usr/share/webmin etc, one per line. If you want a full FS access then input only one option "$ROOT" there, and you'll be happy. But be aware that you will be working with your user privileges, no sudo at this time. If you want to have "root" privileges you'll have to login as "root".

**Comment by Braintelligence** [comment]
Thanks for clearing that up :).
