### ISSUE TITLE
File download / page loading loop

### ISSUE THREAD

**Issue by Goeny** [Real-Gecko/Filemin#2]
When i click a file in the manager, it downloads to my computer and the page "refreshes". But for some reason the page won't stop loading. The loading spinner just keeps on spinning and the filemanager won't come back up.

![loading spinner](https://cloud.githubusercontent.com/assets/3872395/7498709/4f4c503e-f423-11e4-984e-a9e5d76fbb9e.png)

**Comment by Real-Gecko** [comment]
Yeah, you can double click on spinner to close it. That`s known issue, theme developer promised to fix it. The same issue prevents file/folder renaming :(

**Comment by Goeny** [comment]
Allright.
Wasn't sure if it was the theme or the filemanager that caused the issue.
Will wait for theme update then. :)

**Comment by Real-Gecko** [comment]
You can bypass this issue with the following temporary solution:
Manually enter the following address http://yourserver.com:10000/filemin
You'll be directed to bold filemin interface without left sidebar. Renaming and downloading work fine there, as all other functions do.
To go back to Webmin/Virtualmin simply remove "filemin" from your address.
I used this solution myself to bypass icons misbehavior :)

**Comment by iliaross** [comment]
As work around just disable page right loader if you wish

**Comment by iliaross** [comment]
I will fix it in upcoming release 12.10! It will work fine then!

@Real-Gecko I would commit for AJAX file rename, contact me when you have online time for chatting!

**Comment by Real-Gecko** [comment]
I`m online, but cannot connect to jabbers.im

**Comment by qooob** [comment]
I made SSL certificates work yesterday. Can you go to Empathy settings and don't set a tick on ignore SSL certificates? Before that disable the accoun with OFF switch and then when you change that setting set it to on. Your client goes to the port `5220` and Firewall is blocking you! ;)
