### ISSUE TITLE
using filemin in "webmin via httpd"

### ISSUE THREAD

**Issue by harrywwc** [Real-Gecko/Filemin#22]
Hi,
I (am required to) use Webmin via httpd so that I access via "http://myserver.url/webmin/". This gives the issue that when uploading a file using your wonderful tool (thank you E6) I receive a redirect to an invalid url for "uptracker.cgi" - it is looking for "http://myserver.url/uptracker.cgi" when it "should" be looking for "http://myserver.url/webmin/uptracker.cgi" 
The file(s) upload - as long as we leave the "broken" redirect page open until the upload is complete - so there is one workaround :)
Kind regards,
Harrywwc 
p.s. and again, a million thanks for this tool - so much "better" than the Java based clunker that really should have been retired ages ago!

**Comment by harrywwc** [comment]
OK - sorry - not "your" problem - it seems to be an issue with Webmin itself - as that is where the "uptracker.cgi" file resides.
Now to figure it out - sorry for the ID10T moment ;)
.h

**Comment by harrywwc** [comment]
quick update - I am using 0.9.2 (forgot top mention that ;)
I have commented out the onsubmit javascript call to "uptracker" in both of the dialogs.html files in the unauthenticated/templates directory
I will continue (all be it more slowly) looking at why the webmin uptracker.cgi file isn't being found by those html files.
Did I say how much I like this tool? :)
Kind regards,
Harry
(oh, my server is CentOS 6.6 - all up-to-date as of this morning)

**Comment by Real-Gecko** [comment]
I'll look into it. But I think it is more Webmin issue, cause it is really hard to make it work from subfolder.
Navigate to `http://yourserver.url/webmin/updown/` and see if uptracker works there.
