### ISSUE TITLE
Directory permissions

### ISSUE THREAD

**Issue by ChriZathens** [Real-Gecko/Filemin#23]
Hi there and congrats for a new and great looking webmin filemanager.
I have a question.
I am logged in in webmin as user kookoo. The same user exists in unix users.
When I open the original filemanager I am at /
When I open filemin, I am at /home/kookoo

Is this to be expected ?? (I wouldn't have asked if the original file nanager was not displaying /)

**Comment by Real-Gecko** [comment]
Yep it is expected. If there's only one entry in ACL then path showed to user will be relative to allowed path, otherwise he/she will see `/` and navigate relative to it.

**Comment by ChriZathens** [comment]
Thanks!
But can you please explain that "one entry in ACL" part? In Permissions for all modules, while editing the user, the "Root directory for file chooser" is set to /, but the user sees their home dir in filemin
Can I do anything to let the user see a higher path?
Thanks again!

**Comment by Real-Gecko** [comment]
It looks like this:
`/usr/share/webmin`
Multiple entries look like this:
`/etc/nginx`
`/usr/share/nginx`
If you want to grant users full FS access then write $ROOT to ACL.

**Comment by ChriZathens** [comment]
You wrote 
_Multiple entries look like this:
/etc/nginx
/usr/share/nginx_
You mean here??
![capture](https://cloud.githubusercontent.com/assets/8545172/8696599/67289c62-2af6-11e5-9e53-372c2dd3e951.PNG)

And what do you mean with ACL?
If you can elaborate on that I would be grateful...
I don't know where to put this $ROOT to ACL (i'm an inexperienced user - using webmin for a home server)

**Comment by Real-Gecko** [comment]
Navigate to `Webmin->Webmin Users->$YOUR_USERN_NAME->Available Webmin modules (in addition to those from group)` and click `Filemin`, you'll see.

**Comment by ChriZathens** [comment]
Ohhhhhh, OK, got it!!!
Thank you very much for your help - much appreciated!!!

**Comment by ChriZathens** [comment]
EDIT: Problem... I have a hard disk mounted in /mnt/media/downloads and a third one mounted in /mnt/media/downloads/camera
I leave $HOME as is and below I add
/mnt/media/downloads
/mnt/media/downloads/camera
But filemin cannot go past downloads
This is what I see
![capture](https://cloud.githubusercontent.com/assets/8545172/8698988/df7c8b88-2b0a-11e5-86f6-4207bcecdae9.PNG)
When I click on "downloads" it prompts to download the "file". 
Bug?

**Comment by simbus82** [comment]
I'm trying to browse from the "root" of the folders tree... but i have same problems...

**Comment by Real-Gecko** [comment]
What's your module version? What're module settings?

**Comment by simbus82** [comment]
Donwloaded yesterday 0.9.5, webmin package for generic linux (i have a CentOS 6.7)

**Comment by Real-Gecko** [comment]
What're module settings?

**Comment by simbus82** [comment]
I'm using standard setting, and then i have tried some /, /.., ecc (in ACL settings) to hope i can see all server folders like old file manager

**Comment by Real-Gecko** [comment]
Write $ROOT to allowed paths. Be sure it is the only entry.
![123123](https://cloud.githubusercontent.com/assets/2231969/9325320/3f895304-45b3-11e5-9199-d8022bfd869c.png)

**Comment by ChriZathens** [comment]
Kindly reminding you about my previous post... Any ideas there?

**Comment by Real-Gecko** [comment]
Ah yes, sorry, forgot to mension, mount points and links must work in latest version. It was discussed in #20

**Comment by ChriZathens** [comment]
Ahhh, OK...
Thank you very much.

**Comment by simbus82** [comment]
Wow, nice, $ROOT works good! Thanks a lot!

**Comment by ChriZathens** [comment]
Sorry for bothering, but cannot install version 0.9.5...
What I have tried so far
Tried to install via webmin modules --> install --> from http. I get 
Downloading https://github.com/Real-Gecko/filemin/blob/master/distrib/filemin-0.9.5.linux.wbm.gz ..
.. download complete.
Failed to install module from https://github.com/Real-Gecko/filemin/blob/master/distrib/filemin-0.9.5.linux.wbm.gz : Not a valid module file : gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now

Using .deb file I get : 
 dpkg -i webmin-filemin_0.9.5_all.deb
dpkg-deb: error: `webmin-filemin_0.9.5_all.deb' is not a debian format archive
dpkg: error processing webmin-filemin_0.9.5_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 webmin-filemin_0.9.5_all.deb
Any help, please?
Using ubuntu 12.04 64 bit

**Comment by Real-Gecko** [comment]
Open this link in da browser, you'll be surpriesd :D

**Comment by ChriZathens** [comment]
Duhhhh
Officially retarded.... sorry for that - all OK now...
A final q: do you intend to implement the directory size fix proposed from pabloko in issue https://github.com/Real-Gecko/filemin/issues/20 ??? Looks nice idea

**Comment by Real-Gecko** [comment]
Yeah, a bit later, it'll be optional to avoid performance issues.

**Comment by ChriZathens** [comment]
Yeap I see... actually tried it and indeed the first loading takes a while to calculate the size of the folders

**Comment by Real-Gecko** [comment]
It is true for any OS with any FS.
However it is not really frequently used feature.
I think it'll be added after Filemin will be AJAX'ified. Extra button on toolbar like "Show folder sizes" that'll send AJAX request on demand.
Like Alt+Shift+Enter in Total Commander.

**Comment by ChriZathens** [comment]
Ok, then...
Thank you very much!

**Comment by iliaross** [comment]
Filemin will be AJAX'ified in Authentic Theme 15! ;) 

Theme enters final stage of testing, so in couple of days, I think!
