### ISSUE TITLE
Permissions for catalogs and files...

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#27]
Is possible to add batch permissions for many catalogues and files the same as below pictures? This is very important facility in file managers. 

![files](https://cloud.githubusercontent.com/assets/7549566/8856391/78f706be-3162-11e5-8f67-d57b7c910525.jpg)

**Comment by iliaross** [comment]
That would be very cool to have!

**Comment by Real-Gecko** [comment]
Accepted.

**Comment by Real-Gecko** [comment]
How can it look for multiple entries selected?
Files and folders mixed together...

**Comment by Real-Gecko** [comment]
Here are the variants in order of appearance:
`Selected directories and files only`
`Selected files and directorires and files in selected directories`
`All (recursive)`
`Selected files and files under selected directories and subdirectories`
`Selected directories and subdirectories`

**Comment by Real-Gecko** [comment]
The first variant is easy it will do `chmod $perms $cwd/$name` for each entry.

Second variant will do `chmod $perms $cwd/$name` for files and folders and also `find $cwd/$name -type f -exec chmod $perms {} \;` for directories.

Third variant will do `chmod -R $perms $cwd/$name` for dirs and simply chmod for files.

Fourth variant will do same as second except chmodding directories themself.

And fifth one will do `find $cwd/$name -type d -exec chmod $perms {} \;` on all dirs and completely ignore files.

**Comment by Real-Gecko** [comment]
Added in 0.9.4.
