### ISSUE TITLE
Combining action buttons in groups by putting them in dropdown

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#28]
I would like to propose to combine by logical sense that long list of buttons in to a dropdowns (not all, just some). Also, I would like to see some text on the buttons (again not all but some). It will make it easy to use and reduce that long and growing line of top-right control buttons. Adding right click (context menu) would also be good!

**Comment by Real-Gecko** [comment]
We may split 'em in two lines.

**Comment by iliaross** [comment]
No, what is the point? Bootstrap has beautiful dropdowns:

http://getbootstrap.com/components/#dropdowns-example

**Comment by Real-Gecko** [comment]
Yep, can you make 'em compact?
I've currently changed left/right padding of each button from 12 to 8 px, looks not that bad.

**Comment by iliaross** [comment]
You mean to put them in groups?

**Comment by Real-Gecko** [comment]
Yep.

**Comment by Real-Gecko** [comment]
Added in 0.9.4.

**Comment by iliaross** [comment]
THIS IS AWESOME!! Thanks!

**Comment by Real-Gecko** [comment]
Сам тащусь :D

**Comment by iliaross** [comment]
:D Прям как я от темы.. Самовлюбленные чуваки!!

**Comment by Real-Gecko** [comment]
When job is not a job, but pleasure :)))

**Comment by iliaross** [comment]
:+1:

**Comment by Real-Gecko** [comment]
Damn, forgot to make top level menu items translateble, will reopen and fix later.

**Comment by iliaross** [comment]
:)

**Comment by Real-Gecko** [comment]
Made top level menu items translatable in 0.9.5.
