### ISSUE TITLE
Unable to see it in the left menu categories

### ISSUE THREAD

**Issue by ebretteville** [Real-Gecko/Filemin#30]
I dont see the filemin shortcuts in the left menu with the Authentic Theme 14.01 webmin theme. I tried to rename and relocate the entry but no clue.

Anyway after searching filemin I'm able to load the module, its a really great work, more reliable than the java explorer.

**Comment by iliaross** [comment]
You need to make this module available for the current user. Click on your user (Near LogOut button), then in current user settings, go to Available Modules tab and after tick on Filemin. Click save and refresh the page. You will get it next to File Manager link.

**Comment by ebretteville** [comment]
Fine, strange it was ticked but didn't display when i wrote my message. But back after your tips it was ok, thanks. What are yur thoughts regarding the stared and favorites "modules/pages" feature I reported when donating to you for the authentic theme?

**Comment by qooob** [comment]
Be kind opening new issue on Authentic Theme with label improvement. Will talk there, ok? I will delete this message in a bit.

**Comment by ebretteville** [comment]
OK
