### ISSUE TITLE
Error - Perl execution failed

### ISSUE THREAD

**Issue by CyberCam1969** [Real-Gecko/Filemin#31]
First off great job on Filemin, this is the one thing that Webmin has been missing!

I'm just recently change to CentOS 7 (from Ubuntu) and I have installed the rpm package from the webmin site. When I install Filemin it install fine, however when I try to open it I get this error;

"Error - Perl execution failed

Can't locate Data/Dumper.pm in @INC (@INC contains: ./lib /usr/libexec/webmin /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /usr/libexec/webmin/) at /usr/libexec/webmin/filemin/index.cgi line 13.
BEGIN failed--compilation aborted at /usr/libexec/webmin/filemin/index.cgi line 13."

How can I fix this? Is there a Perl module I'm missing?

I never had an issue with Filemin on Ubuntu.

**Comment by Real-Gecko** [comment]
OOOOPS, that's my mistake I forgot to comment out module inclusion I'm using for debug output.
For now I can advise you to install Data::Dumper module from Webmin interface. Or you can wait a day or two until I make new release, it's almost done.

**Comment by CyberCam1969** [comment]
Yep... this did the trick;

```
yum install -y perl-Data-Dumper
```

Thank you for the quick response much appreciated! Cheers!

**Comment by Real-Gecko** [comment]
Fixed in 0.9.4.

**Comment by Real-Gecko** [comment]
You can remove perl-Data-Dumper now :)

**Comment by CyberCam1969** [comment]
Thank you again... cheers!
