### ISSUE TITLE
Doesn't seem to want to install

### ISSUE THREAD

**Issue by jamieisboss** [Real-Gecko/Filemin#34]
get

```
dpkg-deb: error: `webmin-filemin_0.9.4_all.deb' is not a debian format archive
```

when trying the deb and

```
Failed to install module from https://github.com/Real-Gecko/filemin/blob/master/distrib/filemin-0.9.4.linux.wbm.gz : Not a valid module file : gzip: stdin: not in gzip format tar: Child returned status 1 tar: Error is not recoverable: exiting now
```

when trying the wbm 

Any clues?

**Comment by Real-Gecko** [comment]
Navigate here - https://github.com/Real-Gecko/filemin/blob/master/distrib/webmin-filemin_0.9.4_all.deb
And figure out what's the correct download link.

**Comment by jamieisboss** [comment]
Fair enough, I'm at the end of a long night shift, probably could have tried a little bit more before asking here. Having said that, the view raw was the link that worked for me and that's not all that intuitive, maybe a wiki page with links that work would be helpful, github is not all that familiar to me so maybe it's just a thing that people know but I've not come across this before. I guess I'm usually cloning whole repos.

In any case, filemin is awesome and solves a problem for me and i'm sure countless other people so thanks for putting the effort in.

**Comment by Real-Gecko** [comment]
It is the way GitHub deals with binaries, I'm not delighted myself :)
Anyway Jamie Cameron is already planning to include Filemin into Webmin bundle and remove Java FM completely. Soon you won't need to download and install Filemin manually, it'll be onboard :)

**Comment by jamieisboss** [comment]
Even better, that's awesome news, between this and the authentic theme, webmin is a real workable tool again now. Thanks again.
