### ISSUE TITLE
Columns to display

### ISSUE THREAD

**Issue by Doemela** [Real-Gecko/Filemin#35]
In "Columns to display" column Permissions is not showing this is in all themes (Ubuntu 14.04) install is done via dpkg also removed former version and did install again with no luck.

**Comment by Doemela** [comment]
Found it its a typo in filemin-lib.pl on: 
line 192: push @ui_columns, $text{'permissons'} if($userconfig{'columns'} =~ /permissons/);
Must be:
push @ui_columns, $text{'permissions'} if($userconfig{'columns'} =~ /permissions/);

line 257: push @row_data, $permissions if($userconfig{'columns'} =~ /permissons/);
Must be:
        push @row_data, $permissions if($userconfig{'columns'} =~ /permissions/);

**Comment by Real-Gecko** [comment]
Yep, will fix that.

**Comment by Real-Gecko** [comment]
Fixed in 0.9.5
