### ISSUE TITLE
forgot -i for dpkg in README.md 

### ISSUE THREAD

**Issue by Doemela** [Real-Gecko/Filemin#36]
Ubuntu and Debian users may prefer to install with dpkg - webmin-filemin_x.x.x_all.deb.
Must be:
Ubuntu and Debian users may prefer to install with dpkg -i webmin-filemin_x.x.x_all.deb.

**Comment by Real-Gecko** [comment]
Yep, will fix that.

**Comment by Real-Gecko** [comment]
Fixed in 0.9.5
