### ISSUE TITLE
Editor Mode - CodeMirror conflict with Authentic Theme

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#42]
I was working on new release of Authentic and did some other testing with Filemin, found an issue.

CodeMirror mode detection is implemented in Authentic Theme and _running another instance_ and _performing detection_ over again is overkill. Besides theme makes the editor's height as big as possible. You should also add it for non-Authentic Theme's users.

I have created a pull request for this. please review! Thanks!

https://github.com/qooob/filemin/commit/feb2105ffbcc1fc93a57da7c0cd84b072e116011

**Comment by iliaross** [comment]
The fix just does simple testing of var and it's value:

`typeof $__theme_name__ != 'undefined' && $__theme_name__ == 'authentic'`

**Comment by Real-Gecko** [comment]
I want to create new Webmin module that will be central point to all those cool libraries to avoid libraries duplications and possible conflicts.

**Comment by iliaross** [comment]
Not sure what are you trying to say? Does it mean you will make this fix?

**Comment by Real-Gecko** [comment]
Yep, we'll fix that :)

**Comment by iliaross** [comment]
:+1:

**Comment by Real-Gecko** [comment]
Released with 0.9.6

**Comment by iliaross** [comment]
Thanks, bro!
