### ISSUE TITLE
.gz is not .tar.gz - why?

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#44]
When you try to unpack `.gz` you get an error: `application/gzip  archive type not supported yet`? However if you rename `.gz` to `.tar.gz` things just work. Why not try to unpack `.gz` as regular `.tar.gz`, if it works anyway?

**Comment by Real-Gecko** [comment]
Will fix that.

**Comment by iliaross** [comment]
:+1:

**Comment by Real-Gecko** [comment]
Fixed
