### ISSUE TITLE
Filemin in Usermin

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#46]
If you install Filemin under Usermin it gives you an error:

`: Module filemin is for Webmin, not Usermin`

If you install Filemin manually - it just works perfectly!

Please fix, ok!?

**Comment by Real-Gecko** [comment]
Never used Usermin is it intended to install modules too?

**Comment by iliaross** [comment]
Yes, it does! Try and see! ;)

**Comment by Real-Gecko** [comment]
Never tried it, AFAIK from dev documentation there're some differences between Usermin and Webmin modules. I'll look into it, but if adopting Filemin to be installable from Usermin will require it as a dependency it won't be done cause Filemin is designed to work from Webmin at first.

**Comment by iliaross** [comment]
Usermin is Webmin but in usermode. Jamie can and should include it to Usermin! Tell him about this!;)

**Comment by jcameron** [comment]
It should be easy to port this to Usermin as well - I'll do this today.

**Comment by Real-Gecko** [comment]
0.9.6 is out.
