### ISSUE TITLE
Can't modify bitwise

### ISSUE THREAD

**Issue by DraZtiK** [Real-Gecko/Filemin#47]
Just installed Webmin 1.762 on Debian 8 and I received the error when I open the filemin module.

Error - Perl execution failed

Can't modify bitwise and (&) in scalar assignment at ./filemin-lib.pl line 197, near """;"
Compilation failed in require at /usr/share/webmin/filemin/index.cgi line 5.

**Comment by Real-Gecko** [comment]
Did you install release version or cloned git repository?

**Comment by DraZtiK** [comment]
Release from Webmin

**Comment by Real-Gecko** [comment]
Oooops, I think they pushed latest git repo to Webmin bundle that contains some not tested commits.
Remove Filemin module through Webmin interface and install latest stable release from here https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-0.9.5.linux.wbm.gz

**Comment by DraZtiK** [comment]
When I install the downloaded module into Webmin it works fine.

**Comment by Real-Gecko** [comment]
OK then, I will notify Jamie about that. Hope next release of Webmin will have workable Filemin version.

**Comment by Real-Gecko** [comment]
I was really inattentive and only now noticed that 1.762 is dev release of Webmin. So when it'll come to stable release I think they'll inlcude stable Filemin version there.
Nothing to worry about I think, so I'm closing the issue.
