### ISSUE TITLE
Filemin - AJAXed implementation in Authentic Theme 15+ (report Filemin's AJAX related bugs here)

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#48]
I have made an attempt (30+ hours of work :neckbeard: ) to make all functions in _Filemin_ perform in background (without page reload). It accelerates **Filemin** from _3_ to _5_ times depending on the operation, besides making user experience more pleasant.

**Integrated features:**
1. All operations (but file uploads, as they are going to be change soon by Real-Gecko) are AJAXed
2. Back button now works as real back button
3. Error messages are displayed in pop-ups
4. User preferences are saved on folder change/reload
5. Using arrows left/right for changing pages

Recommendations for Filemin developer (Real-Gecko) in regards of Authentic Theme:

**Drop in settings:**
1. Set toolbar style to menu-like view; (default should be set to dropdowns, without ability to change)
2. Disable pagination
3. Items to display per page (as they are automatically saved)

**Add in features/settings:**
1. An interface to remove from favorites. Like having a file in distro `favorites_remove.cgi`, in which you could post  like `?path=/some/path/to/remove/that/is/already/in/favorites` for easier favorites management using Authentic Theme Ajaxed interface

So far Filemin seems to deliver cloud №9 experience in Authentic Theme. In case you have anything to say or bugs to submit please do it here.

**Comment by Real-Gecko** [comment]
If I implement AJAX'ification in Filemin will it interfere with Authentic?

**Comment by iliaross** [comment]
Yes. You should disable all of your ajax functions with theme's provided way, same way as in `cmauto.js`, to prevent conflicts using 

```
if (typeof $__theme_name__ ==  'undefined')
{
   // your code
}
```

**Comment by iliaross** [comment]
..and if you're going to remove basic triggers that you're having now, like functions names from the links or other patterns, it would also break the things up. I would think if Authentic is headed to be the default theme, in both Virtualmin and Webmin, then you shouldn't bother about this (AJAX) stuff and focus more on server side things (bringing new features same way as before, using same logic).

However, I can't alone say or decide on this matter, so consult with Jamie and Joe asking their opinion over that.. mine is that one above, don't do AJAX. In case you want to you can keep my license note there and use my code if you need, no problem with that! ;)

**Comment by andreychek** [comment]
I'll offer that we're looking to make Authentic the default theme, as well as include Filemin in Webmin, within a matter of "days" (meaning soon).

How soon depends on a few outside factors. If all those outside factors come together, it could be as early as this week.

I'd suggest that it's most important that Filemin work well with Authentic. But, we're also looking to maintain compatibility with the original Virtualmin Framed Theme for awhile.  Some people take longer to adapt to change than others, so we want to keep the original theme around for some time :-)

The Virtualmin Framed Theme will be available in Virtualmin for many months after the switch occurs (at least 6 months, probably more), but it's Authentic that will be the default.

Filemin doesn't need to be as optimal/awesome with the Virtualmin Framed Theme (or other themes), but it'd be great if it were at least functional when the theme isn't Authentic.

I guess what I'm trying to say is, if you don't implement AJAX for themes other than Authentic, I don't see that as a problem.  I'd vote for instead adding other features.

**Comment by Real-Gecko** [comment]
OK, old themes are supported of course as much as possible, but most new features go to Authentic part of code. If all AJAX'ification is done on theme side maybe we can skip AJAX'ification of Filemin?

**Comment by iliaross** [comment]
:+1:

**Comment by iliaross** [comment]
How is it (AJAX part), by the way, worked good? ;)

**Comment by Real-Gecko** [comment]
I'm currently trying to deploy dev environment on Cloud9, I'll test it there.

**Comment by iliaross** [comment]
Alright then..

**Comment by Real-Gecko** [comment]
Current master brunch is unworkable :D

**Comment by Real-Gecko** [comment]
Fixed with latest commit, update your copies of master.

**Comment by Real-Gecko** [comment]
Yeah, that looks cool! For file upload I think I'll adopt this library
https://blueimp.github.io/jQuery-File-Upload/
That will be cool too :)

**Comment by Real-Gecko** [comment]
If I copy folder and then paste it somewhere not the folder itself is copied, but it's content.

**Comment by iliaross** [comment]
I would think that same happens in default theme. Sounds like a missed Filemin bug?

**Comment by Real-Gecko** [comment]
https://github.com/webmin/webmin/issues/245
Maybe Webmin issue.
