### ISSUE TITLE
Update information

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#49]
Any chance to have Filemin update information facility like eg. Authentic Theme here?

![fff](https://cloud.githubusercontent.com/assets/7549566/9445636/17bc9bde-4a85-11e5-9b02-4e6da322731b.jpg)

This facility would be cool... ;)

**Comment by Real-Gecko** [comment]
Filemin is in Webmin bundle since 1.762, but it may be unworkable. I think they pushed latest master branch, that were a bit unstable.
Anyway Filemin will be now updated with Webmin itself and next release will contain stable version.
