### ISSUE TITLE
Calculating folder sizes

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#50]
Is possible Filemin calculates the size of each folder? At this moment all folder contains 4KB ;(

![fff](https://cloud.githubusercontent.com/assets/7549566/9446218/472eff12-4a88-11e5-9c95-41fdf33d2490.jpg)

**Comment by Real-Gecko** [comment]
Yep, it was discussed somewhere here in issue queue. I'll add this functionality and I'll make it optional.

**Comment by sz00gun** [comment]
Hi Real-Gecko, and again, 24th of August you promised: "I'll add this functionality and I'll make it optional."

When this happens?

;)

**Comment by jcameron** [comment]
I'd actually recommend against implementing this feature, because getting the true (recursive) size of a folder could be very slow. For example, try running `du -k /usr` and see how long it takes.

Webmin has a module for computing folder sizes, but it does it offline using a cron job.

**Comment by iliaross** [comment]
I can make this feature work using XHR request on demand.. spinner will spin, while calculations are done and then folder size is returned.. easily..

**Comment by iliaross** [comment]
.. I meant in Authentic Theme code.

**Comment by iliaross** [comment]
..and add an icon to the action column or right click context menu.

**Comment by jcameron** [comment]
That would make more sense - but even then, I'd recommend only activating this if a user clicks some button rather than just on a mouse-over, as it could generate a huge amount of disk IO on a system with a large filesystem.

**Comment by iliaross** [comment]
Yes, yes, of course.. I don't like hover effects..

**Comment by sz00gun** [comment]
Great news. Thanks. The community is waiting ;)

**Comment by iliaross** [comment]
Most likely next Authentic Release, like 17.41-17.50. 17.40 is being released in minutes..

**Comment by iliaross** [comment]
Alright, folder size support is added to Authentic Theme 17.52. Please upgrade. 

It works fast and automatically on selecting a row or right clicking (context-menu)

How is it?

**Comment by Real-Gecko** [comment]
LOL, Ilya, I told you not to hurry.
In version 1.0.0 you can get one folder size through properties dialog.
Multiple du -k will be implemented later.
