### ISSUE TITLE
Error: You`re not supposed to be here!

### ISSUE THREAD

**Issue by SavageCore** [Real-Gecko/Filemin#52]
I may have my configuration incorrect but what I am trying to do is login to webmin with a non unix user and browse as root.

Under `Permissions for all modules` in ACL
Browse files as Unix user = root

Under `Filemin File Manager access control options`
Allowed paths = $ROOT
Allow user to work as 'root' = Checked

Is this a configuration error or bug?

**Comment by Real-Gecko** [comment]
It is a design flaw. Initally Filemin was oriented on Virtualmin domain owners that usually have UNIX equivalent. And now problem with virtual Webmin users is growing.
I'll try to solve this issue in next release.
For now I can advise you to convert your virtual user to UNIX user and let him work as root.

**Comment by jcameron** [comment]
The latest Filemin code as checked into github should support this mode of operation already.

**Comment by SavageCore** [comment]
Ah yes that seems to work great, thanks!

**Comment by Real-Gecko** [comment]
Released in 0.9.6
