### ISSUE TITLE
Override files during extracting archives.

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#53]
Is this a bug? During unziping files from archive, overriding files not working....

**Comment by Real-Gecko** [comment]
I actually did not test what exactly happens when files already exist. My mistake.
I think it will be better if user is asked what to do with existing files. Will try to add it later.

**Comment by jes-carr** [comment]
+1 to ask user if it's ok to overwrite

**Comment by amolochitis** [comment]
+1 as well

**Comment by sz00gun** [comment]
+1 as well, even little donation for a developer

**Comment by sz00gun** [comment]
Real-Gecko as you said on 26th of August last year: "Will try to add it later."

Have you even tried?

Any change to do it? This is a last important facility of the Filemin... apart from fixing bugs ;)

Jamie will be proud of you.

Please update us.

**Comment by Real-Gecko** [comment]
Hi there, people.
I've forked Filemin to integrate it with Libraries - another Webmin module I created and still not yet publicly availbable.
It's a second day of work in progress and results are already interesting:
![1](https://cloud.githubusercontent.com/assets/2231969/12318418/397fb224-bac4-11e5-88e9-32d982c28f61.png)
![2](https://cloud.githubusercontent.com/assets/2231969/12318424/48ab1734-bac4-11e5-8385-00bbcff2b4f5.png)
![3](https://cloud.githubusercontent.com/assets/2231969/12318425/4bf67d98-bac4-11e5-84c1-bee93ea0440d.png)
- We now have Bootstrap and Fontawesome even in older themes.
- Filemin does not bundle andy JS libraries anymore.
- Adding new libraries to the code is a piece of cake.
- The amount of code reduced dramatically.

Currently I'm struggling to implent right-click menu, next step will be overriding default theme tables with Datatables, new upload library integration will come after and many more.
I'm planning to bring new usage experience to the next release.
So, please, be patient.

**Comment by iliaross** [comment]
Sasha, not exactly clear - what do you mean `overriding default theme tables with DataTables`? Isn't DataTables are already used in Filemin. Also not clear - are you going to load Bootstrap and FontAwesome for old theme? Hmm.. I wonder what is the practical point of all of this? In my opinion it's better to let the theme do styling, while the module itself should be doing _logic_ rather than _presentation_. 

Anyway, I'm already in the middle of integrating right-click menu for _Filemin_ in _Authentic Theme_ and other features, so please please don't forget not to load those scripts (Bootstrap, FontAwesome and right click menu). 

Please notify us when you release new version, so before it's added to Webmin, I will have enough time to integrate new features!

P.S. Happy New Year! ;)

**Comment by Real-Gecko** [comment]
As you can see Bootstrap and FA are already in use and they're not bundled with Filemin, but connected like this:

``` perl
    @libraries = (
        {
            'name' => 'jquery',
            'files' => ['jquery.min.js']
        },
        {
            'name' => 'bootstrap',
            'files' => ['js/bootstrap.min.js', 'css/bootstrap.min.css', 'css/bootstrap-theme.min.css']
        },
        {
            'name' => 'jquery.contextMenu',
            'files' => ['jquery.contextMenu.min.js', 'jquery.contextMenu.min.css']
        },
        {
            'name' => 'fontawesome',
            'files' => ['css/font-awesome.min.css']
        },
        {
            'name' => 'datatables',
            'files' => [
                'js/jquery.dataTables.min.js',
                'css/jquery.dataTables.min.css',
                'js/dataTables.bootstrap.min.js',
                'css/dataTables.bootstrap.min.css'
            ]
        },
    );

$head = libraries::load_libraries(@libraries);
&ui_print_header(undef, "Filemin", "", undef, 0 , 0, 0, $config_link, $head);
```

**Comment by Real-Gecko** [comment]
What plugin do you use for right-click menu?

**Comment by Real-Gecko** [comment]
Default theme table vary from theme to theme, some theme add annoying JS or completely useless markdown. So I override functions that render ui_tables_header, that only output `<table><tr><td>`

**Comment by iliaross** [comment]
It's just few lines of code. I don't remember really. I think it's called `Bootstrap Context Menu`.

I wouldn't override those function and thus output as it might break default behaviour and it's the theme's work to do it. I don't want to limit you in any way, I'm just saying that making Filemin work the way it is now under Authentic Theme is a very hard work and changing UI is not what I would focus on.

My proposal you do features, I will do design and great UI and experience! :)

**Comment by Real-Gecko** [comment]
Well, there's a lot of work to do, not only visual experience is important, but usability too. JS brings lot of fucntionality to webapps.

**Comment by jes-carr** [comment]
I think that the current UI works just fine for now, but it would be great to have the much needed functionality to allow the users to override files. That would require no UI changes, or just adding a popup to confirm.

**Comment by Real-Gecko** [comment]
Popup to confirm would be ideal, but implementation won't be easy :D

**Comment by iliaross** [comment]
You do the perl part, tell me additional argument that is passed and I'll so it in Authentic Theme. ;)

**Comment by amolochitis** [comment]
Has anybody thought of just adding a property in the settings to dictate
default decompression behavior?

**Comment by Real-Gecko** [comment]
Context menu is done. Be patient.

**Comment by jes-carr** [comment]
Adding the default behavior in the module configuration is a great idea @amolochitis and it won't require any UI changes...

**Comment by Real-Gecko** [comment]
I've just tested issue on my dev Debian 8 and here what I'v got:
- extracting tar.gz overwrites the files
- extracting zip skips

Will be fixed in next release.

**Comment by amolochitis** [comment]
Sounds great!
