### ISSUE TITLE
Very bad bug. IMPORTANT

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#54]
There is a problem with copy CMS websites, eg. Magento...

Please have a look my screen-video to learn more.

http://screencast-o-matic.com/watch/cojO2MfkgD

**Comment by singhdd93** [comment]
webmin/webmin#245

**Comment by Real-Gecko** [comment]
Tis not a bug, tis a feature xD
I'll fix that today.

**Comment by Real-Gecko** [comment]
Fixed in 0.9.6
