### ISSUE TITLE
pagination broke for old themes

### ISSUE THREAD

**Issue by Doemela** [Real-Gecko/Filemin#55]
line 199 - 201 filemin-lib.pl change it back to to old code

**Comment by Real-Gecko** [comment]
I've fixed this in master branch and also added some padding between links.
You can checkout latest branch or just go to module settings and set items per page to something like 500 or 5000 or OVER NINE THOUSAND!!!
xD

**Comment by Real-Gecko** [comment]
OK. I've repacked archive with this new fix.
Download version 0.9.6 again and reinstall.
