### ISSUE TITLE
Making clear currently editing file's name

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#56]
I would like to propose to beautify Filemin file editor's mode to make file and its path in table header, like all-over Webmin. Here is the example in screenshot:

![screenshot from 2015-08-28 14-13-25](https://cloud.githubusercontent.com/assets/4426533/9545169/b352f3b0-4d8f-11e5-83ef-126ac7761be2.png)

Notice where the file name is.. Could ya do dat?

**Comment by Real-Gecko** [comment]
Next minor release :)

**Comment by iliaross** [comment]
:+1:

**Comment by iliaross** [comment]
Well. I already made it differently in Authentic Theme. I will wait for a release preview. I hope it will not bring much breakages! ;)

**Comment by Real-Gecko** [comment]
Looks like screenshot you provided.

**Comment by iliaross** [comment]
Alright, that I understood! Thanks, Sasha!

**Comment by Real-Gecko** [comment]
U'r welcome :)
