### ISSUE TITLE
Uploaded file goes to wrong catalog

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#57]
Using File -> Upload Files in Filemin (0.9.5), I try send this file here:
![file1](https://cloud.githubusercontent.com/assets/7549566/9563614/efa7873a-4e80-11e5-8dc3-b09c6ff46d86.jpg)

but it goes here ;(
![file1a](https://cloud.githubusercontent.com/assets/7549566/9563597/8cf5593c-4e80-11e5-96cc-296d1e89b70a.jpg)

Is this a bug?

Please advise

**Comment by iliaross** [comment]
Hey, that's my bug. I will fix it in version 15.50 very soon! Sorry.

**Comment by iliaross** [comment]
Fixed.. Will work in 15.50! ;) Issue can be close, now!

**Comment by iliaross** [comment]
..and you better update to 0.9.6:

https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-0.9.6.linux.wbm.gz
https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-0.9.6.freebsd.wbm.gz
https://github.com/Real-Gecko/filemin/raw/master/distrib/webmin-filemin_0.9.6_all.deb

**Comment by Real-Gecko** [comment]
What was the deal?

**Comment by iliaross** [comment]
I didn't update on AJAX folder change the path inside of form action..

**Comment by sz00gun** [comment]
Thx.

PS. What a deal you are talking about? :8ball:

**Comment by iliaross** [comment]
He was asking why this was happening.. :D

**Comment by Real-Gecko** [comment]
Everything fine with Authentic 15.50, closing issue.
