### ISSUE TITLE
Number of files and directories in present dir

### ISSUE THREAD

**Issue by marciano1** [Real-Gecko/Filemin#58]
I would like to see at top the number of files and dirs in present dir.
Thanks,
M

**Comment by iliaross** [comment]
I could do it using theme really, unless Filemin dev doesn't mind?

**Comment by Real-Gecko** [comment]
I think it is better not to overload the theme with additional functionality, this will reduce overall supportability.

**Comment by iliaross** [comment]
Agree. Then it's up to you. ;)

**Comment by marciano1** [comment]
Maybe it can be added as optional output in module configuration settings
