### ISSUE TITLE
File Upload Status Not Working in CentOS 

### ISSUE THREAD

**Issue by aatayyab** [Real-Gecko/Filemin#59]
Whenever I try to upload a file, it does not show any status.

**Comment by Real-Gecko** [comment]
What browser do you use?

**Comment by aatayyab** [comment]
chrome 45.0

**Comment by jcameron** [comment]
FYI, I saw this issue too - but only when uploading as a non-root user.

**Comment by Real-Gecko** [comment]
Ah ok, now I understand, it happened before, when I was redeveloping upload.cgi.
I'll try to figure out what's the deal in next release.

**Comment by Real-Gecko** [comment]
For now I can only advise you to monitor newly created file size by hitting "Refresh" button in Filemin toolbar, when it stops growing then your upload is done.
Just a silly workaround xD xD xD

**Comment by Real-Gecko** [comment]
Try to retest the issue when release 0.9.7 comes out.
If you'll encounter it again feel free to reopen.
