### ISSUE TITLE
module not showing in "other" after recommended way to install on Ubuntu

### ISSUE THREAD

**Issue by lisandi** [Real-Gecko/Filemin#63]
We installed filemin on Ubuntu via dpkg like recommended but the module does not show up in the list in section Other on Authentic Theme

**Comment by iliaross** [comment]
You need to Enable it by going to Webmin Users, under Available Webmin modules, find FIlemin and enable it.

**Comment by lisandi** [comment]
Thanks Ilja That was it.

Please add that to the readme as I am sure that more people will have those
problems as they don't find where to enable the theme or module.

Another question would be is it usefull to use the git version or is it
better to stay with the dpgk or wbm version?

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by iliaross** [comment]
It's better address this question to Alexander - the developer... but I guess that he would recommend packages. I also do, because starting from version 16, Authentic Theme will have enormous support (keyboard + shortkeys) for Filemin and we would have to agree on new things and features before updating to make sure things will work smoothly.

**Comment by lisandi** [comment]
Thanks for the info IIja

I hope he also would add again the possibility to create and manage
symlinks as this was very useful in the JAVA filemanager.

Your authentic Theme is really a great asset and HUGE improvement for
virtualmin - I really like it - contrast could be a bit better to make it
more readable on mobile devises when sunlight or other light sources are to
bright. and for the server list it would be better to have identations
separated more clearly either by color or by something n front of the
subservers and alias servers to make it more clearly that they are not n
the main level.

But I really like it Thanks for the great work!

Andi

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

_ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk:  andi@lisandi.com
Facetime:      andi@lisandi.com

---

This email may contain confidential and/or privileged information. If you
are not the intended recipient (or have received this email by mistake),
please notify the sender immediately and destroy this email. Any
unauthorized copying, disclosure or distribution of the material in this
email is strictly prohibited. Email transmission security and error-free
status cannot be guaranteed as information could be intercepted, corrupted,
destroyed, delayed, incomplete, or contain viruses. The sender therefore
does not accept liability for any errors or omissions in the contents of
this message which may arise as a result of email transmission

**Comment by iliaross** [comment]
@lisandi I will keep this in mind and on my todo.

@Real-Gecko Sasha, it's also whould be good to gather all possible UID/GID and add them to the select when changing `chown` instead of writing it manually. It would be fairly easy to do!

**Comment by andreychek** [comment]
Howdy! I believe this particular issue soon won't matter... as Filemin will be included with Webmin by default, and it won't be necessary to perform those steps.

Jamie will have it so that the setup works similar to how the current filemanager works.  Or at least, he should, I'll verify with him that this is the case :-)

**Comment by iliaross** [comment]
:+1:
