### ISSUE TITLE
Can I enable it for Virtualmin users?

### ISSUE THREAD

**Issue by MichaelW1998** [Real-Gecko/Filemin#64]
Hi there,

So, I noticed that Filemin is listed under Others in Webmin. Is it possible to enable it for non-root Virtualmin users (and maybe limit the Filemin access to their own virtual servers?
Would be stupid to give other users root access so they can use Filemin as root.

Cheers!

**Comment by jcameron** [comment]
The next release of Virtualmin will grant access to Filemin to domain owners, with appropriate permissions.

**Comment by singhdd93** [comment]
Waiting for next release. This is the only feature I am waiting for...
Thanks a lot @Real-Gecko @jcameron
