### ISSUE TITLE
Couple things...

### ISSUE THREAD

**Issue by jrossh21** [Real-Gecko/Filemin#65]
In the installation section, please go into detail on how to install this and where it will show up. For instance, being a linux and webmin noob, I would do something like this:

From the Webmin Interface, click through Webmin -> Webmin Configuration -> Webmin Modules
Select the "From ftp or http URL" option and enter this URL: https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-0.9.6.linux.wbm.gz
After it successfully installs, you will see the "Filemin File Manager" module under the "Others" menu.

The other thing is ... after you upload a compressed file (.tar), how do you uncompress it through Filemin?

**Comment by Real-Gecko** [comment]
I'll add usage tips in next release. Filemin will be in next Webmin release, so it'll be installed by default, no more need to provide installation procedure :)

**Comment by jrossh21** [comment]
Oh nice! Looking forward to it!

Also, I figured out how to uncompress .tar files ... rename it to .tar.gz
