### ISSUE TITLE
Copy / Paste folder problem

### ISSUE THREAD

**Issue by simbus82** [Real-Gecko/Filemin#67]
If i select two folders, do a copy and then i want to paste in another folder, i see that are pasted all files (contained in selected folders) losing the folder tree: all files are pasted without folders and are pasted all folders without files inside.
To obtain a correct copy/paste i have to compress folders, paste the archive file and then extract it.

For me is a bug, i think is not intentional, right?

Thanks a lot
Simone

**Comment by iliaross** [comment]
You must upgrade to version 0.9.4, it was fixed there as far as I remember.

**Comment by Real-Gecko** [comment]
Yep, it was not bug, but a feature of Webmin Core :D
Update your Filemin installation and you'll be happy ;-)

**Comment by simbus82** [comment]
Thank you a lot! I think an old upgrade was failed, now is ok! Sorry!

**Comment by simbus82** [comment]
Ehm, another little thing, after pasting folders (version 0.9.6) the owner becomes "root" and not the owner of folder copied.

**Comment by Real-Gecko** [comment]
Yep, as usually if you work as root, every operation will be executed with root permissions, so newly created copies will be owned by root.

**Comment by Real-Gecko** [comment]
Beware that updating module through Webmin interface creates concurrent versions. So maybe updated Filemin is somewhere out there in your Webmin :D
If you update Filemin through Webmin then I advise you to delete old version prior to installing new one.
Or use .deb package if you're on Debian or Ubuntu, it does not have such issue.
Soon Filemin will be bundled within Webmin Core, so there will be no need for upgrade.
