### ISSUE TITLE
Folders tree like old Webmin java filemanager: enhancement

### ISSUE THREAD

**Issue by simbus82** [Real-Gecko/Filemin#68]
Is it possible to have a "folders tree" like the old file manager? Could be very useful for navigate folders without return back every time. Thanks.
Simone

**Comment by Real-Gecko** [comment]
Tis was discussed in forum thread.
This feature will require some redesign to maintain overall compactness of da interface.
If you have any suggestions how to make things nice and clear visually, then be my guest.
I'll think about adding this feature, but no promises of doing it quickly :D

**Comment by ffrewer** [comment]
+1 for this feature request

**Comment by simbus82** [comment]
Maybe something like this Jquery plugin?
http://www.jqueryscript.net/layout/jQuery-jQuery-UI-Dynamic-Tree-View-Plugin-Fancytree.html

**Comment by Real-Gecko** [comment]
Yep, nice plugin, how can we integrate it to the current interface without making it look wobbly?

**Comment by Real-Gecko** [comment]
Planned for 1.1.0

**Comment by simbus82** [comment]
Sorry if i can't help you, i'm not so good with this code!

Thanks for planning this!

**Comment by Real-Gecko** [comment]
It does not matter, cause I already know how to do this :)

**Comment by Real-Gecko** [comment]
Added in 1.1.0
