### ISSUE TITLE
No Decompress Option - CentOS 32 Bit

### ISSUE THREAD

**Issue by amolochitis** [Real-Gecko/Filemin#69]
I can compress files, but then I cannot decompress them afterwards.  Is there a decompress method coming.

**Comment by iliaross** [comment]
In case you're using Authentic Theme there is a [list of shortcuts](https://github.com/qooob/authentic-theme#list-of-keyboard-shortcuts). Other than that there is unpack button near the file name, in action row.

**Comment by amolochitis** [comment]
I just don't see a decompress option in the standard, nor the Authentic theme.  Am I missing something?  I just updated webmin today.

![image](https://cloud.githubusercontent.com/assets/14184449/10352555/7ab853ce-6d15-11e5-82a0-58cc173945be.png)

**Comment by iliaross** [comment]
You probably need to install `unzip` command?

**Comment by amolochitis** [comment]
I have zip/unzip installed on the server.
Package zip-2.31-2.el5.i386 already installed and latest version.
Package unzip-5.52-3.el5.i386 already installed and latest version.

Is there a newer version of filemin that is out there that can extract zip files?

**Comment by iliaross** [comment]
I just double checked and I can see the unpack button. Do you have 32bit OS? In case you're not, then you should also install 64 zip/unzip, I suppose. Other than that, we should see what RealGecko will say.

**Comment by amolochitis** [comment]
I have a 32 Bit CentOS 5.11 that has this issue.  I have not tested it on the 64 bit systems yet.  If this is the case, then it is isolated to 32 Bit OS.  Maybe this issue can get looked at by RealGecko.

**Comment by Real-Gecko** [comment]
Check if you have shared-mime-info package installed, it is available for CentOS 5.
http://pkgs.org/centos-5/centos-i386/shared-mime-info-0.19-5.el5.i386.rpm.html
If not install it.
If it does not help, then download your zip and try to unzip locally. Report results here.

**Comment by amolochitis** [comment]
Well that worked.  Now I can decompress. :)  

Thanks.

Last question.  Do the files in the zip archive overwrite the files in the directory that it is decompressed into if there are files there with the same name(s)?

**Comment by Real-Gecko** [comment]
Well, it is my fault but I did not test it :D
Actually decompression goes through `system()` call, so it is hard to manipulate the process.Somewhere in da forum people complained that ungzipping did not overwrite files. So maybe answer is no.
I personally always prefer to delete files manually before unzipping/untaring to make sure no garbage is left.
However I'll think about implementing confirmation of files overwrite if they exist.
And maybe some kind of "archive explorer", so at least user can see contets of archive.

**Comment by amolochitis** [comment]
Maybe it can be a settings property on the filemin as a radio option button.

Choose the decompression option default : 
1.  Overwrite Existing Files
2.  Do Not Overwrite Existing Files

What do you think?

**Comment by Real-Gecko** [comment]
I think that popup on each unzip/untar operation is better, more flexible. I'll think how to add this functionality.

**Comment by amolochitis** [comment]
That sounds great.  
Thanks
