### ISSUE TITLE
Request ability to manage what mime types activate the edit action/icon

### ISSUE THREAD

**Issue by dlangh** [Real-Gecko/Filemin#70]
I've had a need for a while for some staff to be able to edit (really just copy/paste) intermediate SSL certificate files for our customer sites.  The way I have our system setup is each site on the webserver has it's own folder to store it's certificate files and every site has a file I named intermediate.crt  Using this file manager it would be easy enough for me to show less technical staff where to navigate to find the certificate files, then if they could edit them, simply copy/paste the new intermediate files.  Our customers often change SSL providers so this is an ongoing process for us.

In any event, I found the following section of code in filemin-lib.pl (line 266 of the current version):

if (
                index($type, "text-") != -1 or
                $type eq "application-x-php" or
                $type eq "application-x-ruby" or
                $type eq "application-xml" or
                $type eq "application-javascript" or
                $type eq "application-x-shellscript" or
                $type eq "application-x-perl" or
                $type eq "application-x-yaml"
            ) {
                $actions = "$actions<a class='action-link' href='edit_file.cgi?file=".&urlize($link)."&path=".&urlize($path)."' title='$text{'edit'}' data-container='body'>$edit_icon</a>";
            }
            if (index($type, "zip") != -1 or index($type, "compressed") != -1) {
                $actions = "$actions <a class='action-link' href='extract.cgi?path=".&urlize($path)."&file=".&urlize($link)."' title='$text{'extract_archive'}' data-container='body'>$extract_icon</a> ";
            }

If I added the type 'application-pkix-cert' to the if statement  above, the edit icon activates for that file, but for me to rely on this I'll have to re-apply this each time this module is updated.

It would be great if the list of allowed mime types for this could be something managed in the modules config settings.  This would be useful as I see many other mime types that are essentially text-based files that would be useful to edit.

**Comment by Real-Gecko** [comment]
Yeeeah, nice idea, will add this.

**Comment by Real-Gecko** [comment]
Editable mime types are now provided by CodeMirror, no more need to setup. Grab version 1.1.0.
