### ISSUE TITLE
file editor for filemin

### ISSUE THREAD

**Issue by midol** [Real-Gecko/Filemin#72]
One of the nice features of the file manager is its file editor, very handy for small fixes and testing, there seem to be several available with GPL licensing.

**Comment by iliaross** [comment]
There is file editor, what is missing from your point of view?

**Comment by schmimat** [comment]
I'm missing the posibility to search in the editor.

**Comment by Real-Gecko** [comment]
Ilya implemented this under Authentic, simply press Ctrl + F.
Under other themes you can use your browser's search functionality by simply pressing Ctrl + F too.
Note that in both cases editor textarea must be focused, click on it to make sure it is.

**Comment by iliaross** [comment]
..and to search further (to get next match) just click `Ctrl+G`
