### ISSUE TITLE
Actual folder or file path in html title 

### ISSUE THREAD

**Issue by ffrewer** [Real-Gecko/Filemin#76]
First: many many thanks for the file manager. Great work.

At the moment, if I open filemin in different browser tabs to be able to switch easily between different folder views and/or file editors, I always have the html titles &lt;title&gt;Filemin&lt;/title&gt; or &lt;title&gt;Edit file&lt;/title&gt;.
Would it be possible to add the actual path to the title, e.g. &lt;title&gt;/path/to/folder - Filemin&lt;/title&gt; or 
&lt;title&gt; /path/to/folder/filename - edit file - Filemin&lt;/title&gt;, like here on Github?

It would make it easier to find the right tab while hovering over them.

**Comment by Real-Gecko** [comment]
Nice idea, will add this.

**Comment by ffrewer** [comment]
Thanks. :-)

**Comment by Real-Gecko** [comment]
It turns out to be not easy task, maybe Jamie can advice something?

**Comment by jcameron** [comment]
This is only really possible if the theme doesn't use frames. Otherwise a module (like Filemin) can only set the title on it's inner frame, which doesn't appear in the browser.

**Comment by iliaross** [comment]
Not sure where is the problem here? I will add this to my todo and try to embody this feature.

**Comment by iliaross** [comment]
Jamie, it is possible! 

Sasha, you can easily update title on the parent frame (while being in child's) by doing something like this:

``` JavaScript
window.parent.document.title = '/home/example.com/public_html - Filemin – Webmin version, hostname'
```

Before you do so, you can save the current title and it's hostname to `localStorage` and then use it to append it to the constantly updated path.

Example:

``` JavaScript
localStorage.setItem("initial_title", window.parent.document.title)
```

Later use it as such:

``` JavaScript
/home/example.com/public_html - Filemin – localStorage.getItem("initial_title")
```

> _This is a great idea. I will make theme update the path for all modules on next release._

P.S. Don't forget to flush the Filemin title when user switches to the other module. I think it's better done using the theme as Filemin will not be able to return title back to its initial state, unless tricky usage of `onbeforeunload()` function.

**Comment by iliaross** [comment]
@ffrewer This functionality (Document title for the browser's tab) will be available in _Authentic Theme_ **17.03** (In couple of days) and will work for all other modules/pages across Webmin/Virtualmin/Cloudmin + will show path for Filemin (not only module name).

Thanks for the nice advice on this feature.

**Comment by iliaross** [comment]
It's already out in version 17.03. Please update.

I hope it works well for you!

**Comment by ffrewer** [comment]
@qooob Thanks a lot. Very good work. It will help me a lot.
@Real-Gecko 
I don't know if I'm the only one. But when I open filemin in different tabs, very often I open only the inner frame to be able to use the whole window width.  In this case the tab doesn't have the path in the title. 
I made some tests and it doesn't look difficult. 
E.g. index.cgi, line 18, this should do it:
    &ui_print_header(undef, $path." Filemin", "", undef, 0 , 0, 0, "<a href='config.cgi?path=$path' data-config-pagination='$userconfig{'per_page'}'>$text{'module_config'}</a>"); 

or edit_file.cgi, line 10, this one:
    &ui_print_header(undef, $path.'/'.$in{'file'}.' - '.$text{'edit_file'}, "");

What do you think? Is that overdone?

**Comment by iliaross** [comment]
I have plans to later add tabs support for Filemin (like Nautilus or Double Commander). You will not need extra window then.

**Comment by Real-Gecko** [comment]
Version 1.0.0 show all editable files in named tabs. Go grab it.
![1](https://cloud.githubusercontent.com/assets/2231969/12544416/29c96c1e-c364-11e5-8ca6-556c53e95268.png)
