### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by ffrewer** [Real-Gecko/Filemin#77]
I will provide a german translation file - if you want. It's almost ready, but I have to break the work on it at the moment.

**Comment by Real-Gecko** [comment]
You can provide it as a pull request when it is ready. I will merge it with main branch with pleasure :)

**Comment by Real-Gecko** [comment]
I've merged you pull request, sorry for delay :)
I'll check if all tranlatable strings have corresponding vars in lang file.

**Comment by ffrewer** [comment]
Thanks a lot.
