### ISSUE TITLE
how to unzip?

### ISSUE THREAD

**Issue by fr4nnet** [Real-Gecko/Filemin#80]
i dont see any icon for unzip a zip, tar, tar.gz etc. Thanks for this amazing tool.

**Comment by Real-Gecko** [comment]
Look here
https://github.com/Real-Gecko/filemin/issues/69
Maybe you have similar issue.

**Comment by fr4nnet** [comment]
Nope, I cant resolve this. Tested also with Gray Framed Theme.

I have installed unzip --version
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

Debian Linux 8.2
Webmin version  1.770
Theme version   Authentic Theme 17.00
Kernel and CPU  Linux 3.16.0-4-amd64 on x86_64

**Comment by Real-Gecko** [comment]
Post screenshot.

**Comment by fr4nnet** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/13440068/10688450/a71af578-7974-11e5-8e56-86bb27398864.png)

**Comment by Real-Gecko** [comment]
apt-get install shared-mime-info

**Comment by fr4nnet** [comment]
It works like a charm, thank you

**Comment by Real-Gecko** [comment]
You're welcome :)
