### ISSUE TITLE
Entering directory with Russian name not working

### ISSUE THREAD

**Issue by iliaross** [Real-Gecko/Filemin#81]
I think the bug caused by some JavaScript URI encode function that doesn't do things correctly.

It happens with the Latin extended characters as well. For example, the folder with the name `Ostatní` or `Тест` can not be opened.

https://github.com/qooob/authentic-theme/issues/276#issuecomment-151502895

**Comment by Real-Gecko** [comment]
Hmmm, does it work under old themes?

**Comment by iliaross** [comment]
No

**Comment by iliaross** [comment]
Do you confirm this?

**Comment by Real-Gecko** [comment]
I'll test it later, maybe something was broken while I was adding shiny new features :D
