### ISSUE TITLE
Filemin doesn't save the file lol

### ISSUE THREAD

**Issue by 7starsone** [Real-Gecko/Filemin#84]
Hello,
I'm on CentOS 7 + Webmin/Virtualmin (Authentic theme)
tried on a simple text file... tried to empty and Save...
the animation spinner stays there and nothing else... then, If I click on Close, it correctly closes the file but the file isn't changed at all...
may be an issue by the theme?

Thank you

**Comment by 7starsone** [comment]
don't know why... retried and saved... first time it didn't work... no errors on javascript console
anyway I close this issue for now
bye

**Comment by Real-Gecko** [comment]
Yes, it maybe theme issue. AJAX'ification of Filemin is done on Authentic side, thanks to @qooob :)

**Comment by iliaross** [comment]
I'm beating now with making Collapsible (minimizable) Filemin Editor window, so multiple files could be edited at the same time. If there is a bug which your talking about (however I doubt as it was tested thoroughly) then it should just go.. If I ever finish I'll release it in 17.21 around Xmas! ;)

**Comment by Real-Gecko** [comment]
Nice :)

**Comment by iliaross** [comment]
I can't tell you how annoying this is!! :|

**Comment by Real-Gecko** [comment]
I can imagine :D

**Comment by iliaross** [comment]
:D

**Comment by 7starsone** [comment]
found the issue... lol
it can't save when the file content in the meanwhile is changed...

eg. 
1) you open the file (eg. a text log file)
2) you're reading the file but in the meanwhile the file content is changed by any external event
3) empty the file
4) can't save...

;-)

**Comment by iliaross** [comment]
I have changed this part in the theme... however, I don't beileve it would be happening.. because the Filemin Editor has the filename and it's content and doesn't care if file is changed or not.

**Comment by iliaross** [comment]
See the version 17.21 in couple of days, it will have the ability to use multiple file-editors at once.

**Comment by 7starsone** [comment]
that is, in 17.21 this will behave different? have you tried those steps yourself?

**Comment by iliaross** [comment]
Yes I did. Couldn't reproduce.

**Comment by 7starsone** [comment]
don't know... If I try to save with the php error log or with maillog while are updated... it did it that way
the spinner on the save button stays there rolling and can't save

**Comment by iliaross** [comment]
It shouldn't be the case in 17.21

**Comment by 7starsone** [comment]
If you want I could do a video about it...

**Comment by iliaross** [comment]
Sure, thanks!

**Comment by 7starsone** [comment]
It's weird.. it doesn't do it anymore... there must be something else which may cause that behavior but on javascript console I don't see special errors...anyway, if it happens again I'll let you know

**Comment by 7starsone** [comment]
anyway, this is on console

`Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
https://mydomain.com:10000/index.cgi/?xhr-info=1`

**Comment by iliaross** [comment]
`net::ERR_CONNECTION_TIMED_OUT` means either session is over or just no connecting for your server.. I guess..
