### ISSUE TITLE
installed successfully but not showing in webmin list

### ISSUE THREAD

**Issue by Bulmer** [Real-Gecko/Filemin#88]
I have installed filemin successfully in both my localhost and remote vps webmin, but "Others->File Manager" only shows up in the localhost version. I did also your webmin-libraries as well. I restarted webmin also but it still doesn't show. Any ideas to get it showing on my VPS webmin?

**Comment by Real-Gecko** [comment]
What version of Filemin do you use?

**Comment by Bulmer** [comment]
The one here:
https://github.com/Real-Gecko/webmin-libraries/raw/master/distrib/libraries-1.0.0.linux.wbm.gz

**Comment by Real-Gecko** [comment]
I've just released Filemin 1.0.0 it does not require Libraries module.
If you filemin is not 1.0.0 then grab new version from [this link](https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-1.0.0.linux.wbm.gz) and be happy :)

**Comment by Bulmer** [comment]
Sorry I posted the wrong link. This is the one I installed (the same one you linked):
https://github.com/Real-Gecko/filemin/raw/master/distrib/filemin-1.0.0.linux.wbm.gz
....but like I say, File Manager isn't listed in the Others category.

**Comment by Real-Gecko** [comment]
It might be Filemin File Manager
![3](https://cloud.githubusercontent.com/assets/2231969/12546399/bed57096-c373-11e5-962d-cac20265bf72.png)

**Comment by Bulmer** [comment]
No, its not listed. Only the Java File Manager is listed.

**Comment by Real-Gecko** [comment]
Is it enabled for your user?
Go to `Webmin Users -> {your user name} -> Available Webmin modules (in addition to those from group) -> Others`
![4](https://cloud.githubusercontent.com/assets/2231969/12546612/30718d38-c375-11e5-8e86-43351cb140c6.png)

**Comment by Bulmer** [comment]
Thanks Real-Gecko, that worked. I also had to click "switch to user" from that page as well (even though I was already signed in as that user!?). Your file manager looks like exactly what i'm after and I look forward to using it. Cheers.

**Comment by Real-Gecko** [comment]
Glad to help :)
