### ISSUE TITLE
Perl Error while uploading file.

### ISSUE THREAD

**Issue by timonmentink** [Real-Gecko/Filemin#90]
In the upload.cgi is an error on line 74 and line 80.

line 74:
                          push errors, "text{'error_writing_file'} $path/$file";
must be
                          push @errors, "text{'error_writing_file'} $path/$file";

same error is on lne 80.

**Comment by Real-Gecko** [comment]
Oooops, thanks for pointing that. I'll double check every script :)

**Comment by Real-Gecko** [comment]
Fixed in 1.1.0
