### ISSUE TITLE
Doesn't follow window resize

### ISSUE THREAD

**Issue by chrispolley** [Real-Gecko/Filemin#92]
Using version 1.1.0 (-- Wow!! Great improvement in functionality and UI --) on Chrome 48.0.2564.109m

When resizing the browser window, the interface doesn't react to that event and as a result some controls (e.g. the tool/statusbar at the bottom of the window, scrollbar on the right, etc.) become unusable if the new window is shorter or narrower, since the UI seems to suppress native browser scrollbars.

Workaround:
If the window is narrower but not shorter and the file tree was hidden at the time of the window narrowing, the hide/unhide tree button at the bottom left will repaint the (tabs-container) file list to match the current window width but will not adjust the outer element (div.container-fluid) size to conform to the new body height.

Note also that if the body window is resized to be narrower than it was at initial load and the file tree is visible, the tabs-container element reflows to below filemin-tree.

**Comment by Real-Gecko** [comment]
Yep, I spend a lot of time syncing different tab types to be same width/height. Treeview caused a lot of trouble, bottom status bar was jumping up and down, that was fun :D

So I did not add `window.onresize` event handling cause I was exhausted.

That will be added in next minor release, of course, cause leaving it like so is no good.

For root user you'll get notification about available update on Filemin launch when that happens  (Webmin main window, not Filemin one) .

Until that time I got a better advice how to bypass this issue: if you don't have any of 'Search' or 'Editor' tabs open, then you can just hit F5, all your 'Navigator' tabs will be restored and Filemin will adjust it metrics to browser viewport.

![6](https://cloud.githubusercontent.com/assets/2231969/13116218/3afe9a86-d5c5-11e5-8f6b-a12e5d261328.png)
![7](https://cloud.githubusercontent.com/assets/2231969/13116227/4077098a-d5c5-11e5-8395-709fc11f5553.png)

**Comment by chrispolley** [comment]
Yes, that works also, since you have the persistence across sessions
implemented (very nice, that :) )

**Comment by Real-Gecko** [comment]
Cool ideas come during testing routine :D

**Comment by Real-Gecko** [comment]
Fixed in version 1.1.1.
Login as root and go to Filemin page, you'll be prompted for update.
