### ISSUE TITLE
Chinese characters are not displayed properly

### ISSUE THREAD

**Issue by stbo** [Real-Gecko/Filemin#93]
It fails,I used in Webmin 1.780.For example,I have a filename is "中文",It displays an alert "utf8 "\xBC" does not map to Unicode at /usr/lib64/perl5/Encode.pm line 174".

**Comment by Real-Gecko** [comment]
Does it happens when you open the folder containing "中文"?

**Comment by stbo** [comment]
If I open the folder that contains file name "中文",it displays an error.

HTTP/1.0 500 Perl execution failed Server: MiniServ/1.780 Date: Mon, 22 Feb 2016 09:32:43 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed

utf8 "\xBC" does not map to Unicode at /usr/lib64/perl5/Encode.pm line 174.

**Comment by Real-Gecko** [comment]
Here are my language settings in `Webmin Configuration`, note that I have `UTF-8` version of language set:
![8](https://cloud.githubusercontent.com/assets/2231969/13215184/db239fb4-d97d-11e5-96a2-be2b44dc7bf0.png)
As a result I can create a folder "中文", a file "中文", I can edit it and I can search for "中文" :))))
![9](https://cloud.githubusercontent.com/assets/2231969/13215224/1123ddfe-d97e-11e5-9749-0471cd44c2a8.png)
Try setting your language like this:
![10](https://cloud.githubusercontent.com/assets/2231969/13215243/2fbb81fe-d97e-11e5-8838-95983a4fde64.png)
And by the way, try upgrading Filemin to 1.1.0, if you did not before :)))

**Comment by Real-Gecko** [comment]
Closing as I can not reproduce.
