### ISSUE TITLE
Global Access Control Options - New Virtual Host

### ISSUE THREAD

**Issue by assadnazar** [Real-Gecko/Filemin#94]
Hi Real-Gecko,
First of all, this was the most needed feature in virtualmin. Thumbs up for you....
1. First thing is that I need to select filemin for each existing user in webmin->webmin users and select filemin for the user. How can I enable filemin for all existing and future virtual host users?
2. Also, when a virtual host gets into the filemin, they get all the files in the filesystem and are not being restricted to their home directory. Why is it behaving like that? 

> Update: I have figured out that I have to go to Filemin File Manager access control options for each user to restrict him/her to his/her home directory. Is there any global access control options for the module?

For a reference please see below images:

![filemanager output for virtual host user 1](https://cloud.githubusercontent.com/assets/8438463/13460365/e5392a62-e09b-11e5-902b-a7ccb5d057f7.JPG)
![filemanager output for virtual host user](https://cloud.githubusercontent.com/assets/8438463/13460366/e53afe64-e09b-11e5-8149-36f0666eb96c.JPG)

Thanks in advance...

**Comment by Real-Gecko** [comment]
Hello there! Virtualmin support was added not by me, but by Jamie himself :)
If your server had lot of vhosts before the feature was added then you need to do some steps, to make things right:
- Navigate to `/etc/webmin/filemin` and remove ALL *.acl files.
- Go to `Virtualmin Configuration` and change something that will trigger `Virtualmin's configuration has not been checked since it was last updated. Click the button below to verify it now.` message. For example you can change `Extra Webmin modules for server administrators`. You can change setting back later. The most important is to click `Re-check and refresh configuration`.

After that Virtualmin will recreate every needed ACL for Filemin and every new domain created will have correct ACL.
Report back if you succeed :)

**Comment by assadnazar** [comment]
Sorry for being so noob but can you guide me how can I change `Extra Webmin modules for server administrators`

> UPDATE: got the option and did as you suggested. but now, i have all the acls created in the `/etc/webmin/filemin` folder for each vhost, but the user can access other hosts and are not restricted to their `$HOME`. See attached image:

![update2](https://cloud.githubusercontent.com/assets/8438463/13494671/8d9668a2-e167-11e5-95b4-3d0d04f14324.JPG)

The user shamimart can navigate to root (user directory aurge is shown in the picture)

Also, can you tell me when i install the module from webmin modules option, should i select `Grant access only to users and groups` or `Grant access to all Webmin users` for proper application.

Right now i Selected `Grant access only to users and groups` and in text box admin user is written.

**Comment by Real-Gecko** [comment]
Yep, 'admin' only is a good option, granting access for everyone is a bad idea, as by default Filemin allows to work users as 'root' :D
And about ACL, can you show me contents of any of ACL files? Webmin deals with Virtualmin domain owners himself, so everything should be correct. Here is the example of one in my production server

```
# cat realgecko.acl
work_as_root=0
allowed_paths=/home/realgecko
work_as_user=realgecko
noconfig=1

```

**Comment by assadnazar** [comment]
Thanks for the reply.

but this is getting wierd now:

My acl for a vhost is as follows:

```
root@server /etc/webmin/filemin # cat demo.acl
noconfig=1
```

Also, now i can't list the files. Refer to the following image:
![update3](https://cloud.githubusercontent.com/assets/8438463/13521537/22381034-e20b-11e5-84fb-56a2e573a883.JPG)

**Comment by Real-Gecko** [comment]
What's your Webmin and Virtualmin version?

**Comment by Real-Gecko** [comment]
By the way, you can not list files because you have no 'navigator' tabs open. Click on "+" to open one :D

**Comment by assadnazar** [comment]
Webmin Version: 1.782
Virtualmin Version: Dont know how to check the version

**Comment by assadnazar** [comment]
just updated webmin and good thing is that the filemin is opening on the same page now... Thumbs up for you.

But a limited user is still not jailed to their home directory. Refer to the picture below:
![update4](https://cloud.githubusercontent.com/assets/8438463/13523039/eb452f3a-e214-11e5-987a-df0c42c2b42f.JPG)

ACL for this user is as follows:

```

root@server /etc/webmin/filemin # cat shamimart.acl
noconfig=1

```

Is there any global setting for filemin? Java file manager locks the user to their home directory but filemin does not

**Comment by Real-Gecko** [comment]
LOL, after upgrading Webmin you downgraded Filemin, as latest Webmin still does not have latest Filemin in bundle. Gimme few hours so I can reproduce automated ACL creation by latest Webmin.

**Comment by assadnazar** [comment]
lol... Real-Gecko

Btw, i changed virtualmin configuration and now the ACL generated are ok. see below:

```
root@server /etc/webmin/filemin # cat albasr.acl
work_as_root=0
allowed_paths=/home/albasr
work_as_user=albasr
noconfig=1
```

and the users are being jailed now.

Should I try deleting the module and installing again?

**Comment by Real-Gecko** [comment]
You can just install new version it will overwrite already existing.

https://github.com/Real-Gecko/filemin/wiki here's the installation manual.

**Comment by assadnazar** [comment]
Thanks Real-Gecko
Everything seems to be working as expected now.
![update5](https://cloud.githubusercontent.com/assets/8438463/13524110/19387324-e21b-11e5-88ff-c2920ce8bb2e.JPG)

**Comment by Real-Gecko** [comment]
You're welcome :)
