### ISSUE TITLE
Add Uncompress feature and button

### ISSUE THREAD

**Issue by dzmitar** [Real-Gecko/Filemin#95]
Please, add Uncompress feature and button.
Thanks!

**Comment by Real-Gecko** [comment]
What's your system, what Filemin version, is `shared-mime-info` package installed in your system?

**Comment by dzmitar** [comment]
1. Debian5 Lenny
2. Not clean Filemin, but Usermin panel 1.690
3. shared-mime-info package is not installed.

**Comment by Real-Gecko** [comment]
http://pkgs.org/download/shared-mime-info
