### ISSUE TITLE
Filenames not properly escaped in delete dialog

### ISSUE THREAD

**Issue by jcameron** [Real-Gecko/Filemin#98]
See https://sourceforge.net/p/webadmin/bugs/4719/ for the details. But basically, a file named like :

`tricky_<p onmouseover=alert(1)>.txt`

will generate an alert when moused over in the deletion popup.

**Comment by Real-Gecko** [comment]
I get
`Error 403
Read access required`
When I open this bug.
But I understand where's da problem. I'll try to fix it today.

**Comment by Real-Gecko** [comment]
Fixed in version 1.1.1.
