### ISSUE TITLE
Copy/Cut and Paste doesn't work

### ISSUE THREAD

**Issue by Anialation81** [Real-Gecko/Filemin#99]
Copy/Cut and Paste has never worked for me and other people I work with in Filemin on CentOS 6 and 7. We have been using Filemin since before it was included in Webmin. No matter what destination you select, this error always comes up:
"Following errors occured while performing operation
Pasting to the same directory makes no sense"

Also, the old Java File Manager allowed copying and pasting into the same folder but it would ask for an alternate file name. That made it very easy to do a quick backup of an individual file while leaving it in the same directory. In that situation pasting into the same directory does actually make sense since it's the only way to duplicate a file.

**Comment by Real-Gecko** [comment]
Will add this to 1.1.2

**Comment by iliaross** [comment]
@Anialation81 With _Authentic Theme_ 17.80+ you will be able to paste to the same folder with new name: (using default distribution of Filemin (0.9.6))

https://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-pasting-files-with-the-same-name-into-current-directory.webm

:wink:

**Comment by iliaross** [comment]
..this will also work for directories..

**Comment by iliaross** [comment]
..and when copying to the other directory, there will be a prompt for replacing/copying with new name..

http://rostovtsev.ru/pub/src/authentic/17.80b/file-manager-pasting-files-with-the-same-name-into-different-direcotry-using-prompt.webm

**Comment by Real-Gecko** [comment]
What's the content of yours `~/.filemin/.buffer`?

**Comment by Real-Gecko** [comment]
Version 1.1.2 allows copy/paste to the same directory, this will create something like this `filename_copy.ext`. Go grab it.
